### ISSUE TITLE
Command Line Interface for Hydrus

### ISSUE THREAD

**Issue by chirag-jn** [HTTP-APIs/hydrus#100]
### I'm submitting a 
- [ ] feature request.

In the Wiki page, there's an idea related to "Designing Command Line Interface for Hydrus"
I found this very interesting and matched my skill set. Can you please tell me, is there any limitation on which tool we have to use to make the command line interface? I have started working on developing a command line interface for Hydrus, and has already taught me a lot about how to write test cases and organise files for a project.

### Do you want to work on this issue ?

yes

**Comment by palnabarun** [comment]
Don't we already have an issue(#64) on this?

**Comment by chirag-jn** [comment]
Hi @xadahiya, I was thinking about developing the command line interface using docopt, and have started working on it too. 
The existing project structure is perfect for using the docopt library.
Few things were required like moving the code in main.py from 
if __name__=="__main__" block to a function named main.
Can you tell me what all options are required in the command line app?

**Comment by Mec-iS** [comment]
@palnabarun as far as i understand this is using a different CLI library. Let's see which one is the best fit for `hydrus` codebase. 

Furthermore the CLI effort is related tohttps://github.com/HTTP-APIs/documentation-hydrus/issues/6 defining a worflow leads directly to defining a commands calking pattern

**Comment by chirag-jn** [comment]
Yeah!
@Mec-iS I am using docopt library while issue #64 is regarding using Click library.
By the way, thanks for the invite!
I will shortly reply with a demo of command line interface for Hydrus using docopt.

**Comment by palnabarun** [comment]
@Mec-iS  `docopt` is good to begin with. We can understand the workflow and the design. `click` has more abstractions that can be used later.

**Comment by chirag-jn** [comment]
@palnabarun if docopt solves the complete purpose, is there any need to use click?

**Comment by palnabarun** [comment]
We should try to keep the design as simple as possible.

So, if `docopt` is doing all that we need, we might not need to use `click`.

**Comment by chirag-jn** [comment]
By design, you mean file structure?

**Comment by palnabarun** [comment]
No. I meant the design of the CLI.

**Comment by Mec-iS** [comment]
No, that's "layout" or "directory structure". With design I mean defining the full procedure with all the steps needed:
> 1. the API designer write a SWAGGER/OpenAPI JSON document that describes his/her API (yet to be implemented, hopefully this year. Please consider submitting an application for this)
> 2. `hydrus` parser will parse this JSON into a HYDRA API documentation ([example here](https://github.com/HTTP-APIs/hydra-flock-vocab/blob/master/hydra_flock.jsonld)) 
> 3. `hydrus` deploys the Web server byt parsing the outcome at 2.
> 4. `hydrus` serves the API
> 5. HYDRA-aware generic clients can use the API

Each of this steps should have its own command, and in hhe end a command that automates all by executing all the commands in the same pipeline.

**Comment by chirag-jn** [comment]
Oh. I will surely tell if docopt is able to solve this purpose.

**Comment by malgamves** [comment]
I feel it would be counterproductive to use different tools. Could we decide on one?

**Comment by chirag-jn** [comment]
Hi @malgamves 
Actually, we are deciding if click would be better or docopt or anything else.

**Comment by malgamves** [comment]
Sure! Waiting for the conclusion so I can get started contributing.

**Comment by chirag-jn** [comment]
@malgamves, what do you mean by "I can get started contributing?". I am already working on it.

**Comment by malgamves** [comment]
@chirag-jn I mean, I'm ready to help, if you'll need any.

**Comment by Mec-iS** [comment]
This is duplicate for #64
