### ISSUE TITLE
Hydrus dependencies are not installed automatically with distutils in setup.py

### ISSUE THREAD

**Issue by suryatejreddy** [HTTP-APIs/hydrus#102]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
distutils does not support `install_requires()`. It gives a warning when you try to install hydrus using setup.py and the dependencies are not installed. The user will have to install the dependencies using the requirements.txt file.

### Expected Behaviour:
All the dependencies must be installed automatically when we setup hydrus. 

### Steps to reproduce:
Run the setup.py file as `python3 setup.py install`.

### Do you want to work on this issue?
yes

We can move to setuptools (https://packaging.python.org/key_projects/#setuptools) which supports `install_requires()` and will further ease the process of setting up hydrus for pip as a package.  
https://packaging.python.org/discussions/install-requires-vs-requirements/.

**Comment by ashwani99** [comment]
Using `setuptools` makes more sense. `setuptools` also has a neat way to include `packages` using `find_packages`

**Comment by xadahiya** [comment]
Setuptools is not a part of Python standard library because it's maintained by a 3rd party rather than Python core team. Each of them has their own pros and cons. See this https://stackoverflow.com/questions/25337706/setuptools-vs-distutils-why-is-distutils-still-a-thing
I think we should discuss this first. @Mec-iS  @chrizandr  What do you think?

**Comment by Mec-iS** [comment]
To give some context: http://lucumr.pocoo.org/2012/6/22/hate-hate-hate-everywhere/
I always tend to choose anything that is provided with the Standard Library.

**Comment by suryatejreddy** [comment]
I agree with you, we should always prefer the Standard Library over 3rd party libraries. Although https://docs.python.org/3.5/library/distutils.html says that "pip installer runs all setup.py scripts with setuptools, even if the script itself only imports distutils". What do you think about this @xadahiya @Mec-iS .

**Comment by Mec-iS** [comment]
@suryatejreddy Python packaging has many different nuances. Check all the documented experiences for this argument like [this one](https://github.com/pypa/setuptools/issues/960) and provide a solution that works for `hydrus`. The only constraint I see is that everybody should be able to `pip install hydrus` in a virtual environment and have the code to run the server (or in future the CLI). If any other command will be needed we can document it, the installation procedure can be two-three commands but it has to be consistent in terms of ease for the user.

**Comment by Mec-iS** [comment]
Merged
