### ISSUE TITLE
Implementing Redis datastore

### ISSUE THREAD

**Issue by sandeepsajan0** [HTTP-APIs/hydrus#110]
### I'm submitting a 
- feature request.
Support Redis as Graph database.
### Current Behaviour:
Hydrus uses a relational database model to store graph data which have many limitations in querying and data accessing like scalability, null factor and time taking querying process.
### Expected Behaviour:

Switch to a graph database like Redis. Its main features include Simple, fast indexing and querying, Data stored in RAM and etc. It will also help in the implementation of Better API querying.
### Steps to reproduce:

Use Hexastore as a data structure and Cypher as a query language.
We will discuss here the steps how we can proceed and add this feature. So, everyone please help me in implementing this feature. I read about Redis, Cypher and Hexastore. Now I want to know that how I can implement those things in this codebase.
### Do you want to work on this issue?

Yes, I am working on this.

**Comment by Mec-iS** [comment]
Please make a comprehensive list of the tools you are thinking about using.

As far as I understood you want to use Redis 4.0 and add redisgraph.io module. There are many other ways of storing/querying a graph in Redis; for the sake of your application, it would be nice to cover the different possibilities to have a clearer picture. You can start with a naive implementation (like a prototype) about using simple tuples or Redis built-in data structures, and then raise the bar to understand how `redisgraph` internals work. You can create your own repository for researching purposes, running queries and tests on a local db instance. For this sake (in later times) it would be nice also to have some automation in creating a VM (Docker or Vagrant) and provisioning scripts to install the needed Redis version. 
As much you can write down about these subjects, more possibilities your application is going to have.

Thanks for dedicating time to this task.

**Comment by videetssinghai** [comment]
Is this issue already assigned to sandeepsajan0 or I can apply for it in GSoC 2018?

**Comment by Mec-iS** [comment]
there is no connection between Github issue and GSOC applications. Please read https://github.com/HTTP-APIs/hydrus/wiki/Starting-Material

**Comment by vddesai1998** [comment]
Are we going to use Redis as a 1st class database?

**Comment by sandeepsajan0** [comment]
++UPDATE++
Hey @Mec-iS, I have used Redis built-in data structure with redis-cli and also by creating [a repo](https://github.com/sandeepsajan0/redis_implementation)(a prototype) in which data is stored, which is getting from the web(simple html page) in Redis.
I have used string, sets, sorted sets, lists, and hashes(usually uses as the tuple). These all have its own requirements and properties and I conclude, hashes are the best option for representation of the object. And now, I am trying to implement graph(redis-graph) as data representation but I got an error at the time saving the graph and I also trying to fix it. I will update it soon.
+++
Provide suggestions to proceed ahead.

**Comment by Mec-iS** [comment]
@vddesai1998 it is not decided yet, depends from proposals and how the implementation goes on. We may have different layers implemented with Postgres and Redis.

@sandeepsajan0 you have already much material. Focus on writing a good proposal.

**Comment by sandeepsajan0** [comment]
hey @Mec-iS  as I read about Redis in a blog that

> These are the two primary reasons Redis sucks as a primary store:
>  -You have to be able to fit all your data in memory, and
>  -If your server fails between disk syncs you lose anything that was sitting in memory.

So, we should use Redis with existing database or we can use Redis as a primary database?

**Comment by vddesai1998** [comment]
@sandeepsajan0  I already have asked Lorenzo about it and he said we should include it in our proposal and then we'll decide

**Comment by Mec-iS** [comment]
@sandeepsajan0 Redis is completely safe at the same level of a SQL database if we take some strong design decisions since the beginning. Everything you heard can be avoided by setting Redis properly and provide *replication* and *write-to-disk policies*. Redis is designed to support natively these features. Every DBMS is a single point of failure if it is run a single instance on a single machine. With a master-slave configuration Redis provides the same level of resilience of any other datastore.

As specified, there isn't anything set yet. We may decide to use Redis only as a cache in the beginning.
