### ISSUE TITLE
Typo in Usage of Wiki

### ISSUE THREAD

**Issue by ntkomata** [HTTP-APIs/hydrus#113]
in the `Adding Classes and Properties` section <br>
`properties = doc_parse.get_all_properties(doc.generate())` will raise a TypeError, and I checked the code and found the right parameter should be `classes` defined above.

**Comment by ntkomata** [comment]
The typo is found in <a href='https://github.com/HTTP-APIs/hydrus/wiki#usage'>https://github.com/HTTP-APIs/hydrus/wiki#usage</a>

**Comment by chrizandr** [comment]
Changed, thanks.
