### ISSUE TITLE
Write views

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#12]
Write the REST API views to serve the data with method GET, POST, PUT as defined in #3

**Comment by xadahiya** [comment]
## First we need some way to convert the owl based `SpaceCraft` and `Subsystems` vocabs to Hydra based `Api documentation`.
### Following the design guidelines described in [#3](https://github.com/HTTP-APIs/hydrus/issues/3) and Markus Lanthler's [event api example](http://www.markus-lanthaler.com/hydra/event-api/), I propose the following endpoints for the hydrus server.

- **Main API entrypoint** _/api/_ [GET]
The main entrypoint should provide atleast ` @context - Entrypoint context's location`, `@id - Application's IRI` , and `location of various endpoints`.

**Sample entrypoint from `event-api` example**
```json
{
  "@context": "/hydra/event-api/contexts/EntryPoint.jsonld",
  "@id": "/hydra/event-api/",
  "@type": "EntryPoint",
  "events": "/hydra/event-api/events/"
}
```

- **COTS endpoint** _/api/cots/_ [GET, PUT, PATCH, DELETE]
This endpoint will handle operations related to COTS ( Commercial Off The Shelves (COTS) spare parts). Each part will have a `<id>` as identifier. The part can be any subsystem(defined as classes) in the [Subsystem vocabulary](http://ontology.projectchronos.eu/documentation/subsystems).
- **Spacecraft endpoint** _/api/spacecraft/<id>_ [GET, PUT, PATCH, DELETE]
This endpoint will handle operations related to SpaceCrafts . Each SpaceCraft represents an assembled group of COTS that can be used to make up an actual satellite. Each SpaceCraft will have a `<id>` as identifier. The SpaceCraft can be any spacecraft type (defined as classes) in the [Spacecraft vocabulary](http://ontology.projectchronos.eu/documentation/spacecrafts).
- **EntryPoint context** _api/contexts/EntryPoint.jsonld_ [GET]
The EntryPoint context provides information related to `Hydra core vocabulary location`, `Api's vocab location`, `information related to various endpoints`.

**Sample entrypoint context from `event-api` example**
```json
{
  "@context": {
    "hydra": "http://www.w3.org/ns/hydra/core#",
    "vocab": "http://www.markus-lanthaler.com/hydra/event-api/vocab#",
    "EntryPoint": "vocab:EntryPoint",
    "events": {
      "@id": "vocab:EntryPoint/events",
      "@type": "@id"
    }
  }
}
```
-  **API vocab** _api/vocab#_ [GET]
The vocab defines `Api documentaion`, `Supported operations` and information related to various endpoints.

-  **COTS context** _/api/contexts/Cots.jsonld_ [GET]
 Cots context provides information and properties related to Cots objects.

**Sample context from `event-api` example.**
```json
{
  "@context": {
    "hydra": "http://www.w3.org/ns/hydra/core#",
    "vocab": "http://www.markus-lanthaler.com/hydra/event-api/vocab#",
    "Event": "http://schema.org/Event",
    "name": "http://schema.org/name",
    "description": "http://schema.org/description",
    "start_date": {
      "@id": "http://schema.org/startDate",
      "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "end_date": {
      "@id": "http://schema.org/endDate",
      "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
    }
  }
}
```

-  **SpaceCraft context** _/api/contexts/Spacecraft.jsonld_ [GET]
Spacecraft context provides information and properties related to Spacecraft objects.

**Comment by Mec-iS** [comment]
@xadahiya The output of views has to be better formatted using contexts.
The `@type` property is required by JSON-LD spec. In general it is not strictly required to return JSON-LD, for now we can return just JSONs.
