### ISSUE TITLE
Unexpected status code returned for non-existent collections in the database

### ISSUE THREAD

**Issue by alohamora** [HTTP-APIs/hydrus#122]
### I'm submitting a 
- [x] bug report.

### Current Behaviour:

Unexpected status code returned by the server:
Currently the hydrus server returns a `status code 405` for non-existent collections in the database.
![screenshot from 2018-02-25 00-19-08](https://user-images.githubusercontent.com/30872134/36633823-98b71a6c-19c1-11e8-9126-f0bd1ea2ab87.png)

### Expected Behaviour:

The server shall give a response with `status code 404` for these endpoints.

### Steps to reproduce:

To fix this behaviour we can add an `additional return value`  in the `checkEndpoint` function
[checkEndpoint](https://github.com/HTTP-APIs/hydrus/blob/master/hydrus/app.py/#L47)
which denotes the `expected status code` to be returned and abort that request with that status code.
### Do you want to work on this issue?

yes

**Comment by tibi77** [comment]
can i work on this?

**Comment by Mec-iS** [comment]
This has been merged with #125, so it is fixed.
