### ISSUE TITLE
Generating user nonces for better security

### ISSUE THREAD

**Issue by IamRaviTejaG** [HTTP-APIs/hydrus#123]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:
Currently, the feature is still in TODO.

https://github.com/HTTP-APIs/hydrus/blob/f88d0d06933ec0d426bd7d6df51f2972fd389a40/hydrus/data/user.py#L22

### Expected Behaviour:
We can add a unique nonce by using random numbers generated using a seed, which can be the sha224 digest of user id or any other parameter.

### Do you want to work on this issue ?
Yes

@Mec-iS Please elaborate on this TODO.

PS: Working on this. PR coming up in a while.

**Comment by Mec-iS** [comment]
duplicate #124

**Comment by Mec-iS** [comment]
As specified in PR:

> I think this needs to be part of a mechanism of 2-factors authentication.
When client and server handshake, the server return an header with a nonce. Then the client authenticates with username, password and nonce. Once the client in authenticated, the server returns a (expiring) token so the client can authenticate with that, without the need for username and password.

> This is not an easy issue, take your time.

**Comment by alohamora** [comment]
@Mec-iS The 2 factor authentication shall be used with `Basic authentication`  or `Digest authentication`??

**Comment by alohamora** [comment]
And how should we send the token to the authentic user??

**Comment by Mec-iS** [comment]
The simplest procedure we can implement is:
* client makes a request
* server responds with a randomly generated string (nonce)
* client passes username password and nonce 
* server checks credentials and nonce and responds with a token that expires in X days
* the client can connect to the endpoints using the token. When the token expires, the procedure is repeated

This way the process of Authentication and the process of Authorization are segregated and there is less password sharing because authorization is token-based.

**Comment by alohamora** [comment]
@Mec-iS For now, I have made a PR #144 which supports the following implementation:

- client makes a request
- server responds with basic authentication challenge (wihout a nonce)
- client passes username and password 
- server checks credentials and responds with a token (valid for infinite days)
- the client can connect to the endpoints using the token.

**Comment by IamRaviTejaG** [comment]
@Mec-iS How about using PGP? The client generates a key pair which is stored locally. The server will have it's own key pair. The client makes a request intended to the server which contains the data and once validated on the server, the server responds with a token. This reduces the load on server (no need to generate the nonce), and furthermore, any communication between the client and the server can also be secured via PGP.

**Comment by alohamora** [comment]
I was thinking to shift to `Digest authentication ` to implement nonce based authentication, in that the server shall respond with a nonce and the client shall respond with a cumulative hashed response of the password,username and nonce. @Mec-iS what do you think about this??

**Comment by Mec-iS** [comment]
At the moment we don't have any solid and tested authentication method, so these considerations can be postponed.

Wait to have a working and merged basic solution, then you can think about adding complexity. For now generating a simple random string as nonce is fine (nonce expires in few minutes), the username and password can or cannot be encrypted using the nonce as a seed. Using digests is just a way to obfuscate  password so it is not a issue at the moment as everything should already work on SSL. After a basic system is working we can move into something more similar to OAuth and then add layers of complexity with more sophistication.

**Comment by Mec-iS** [comment]
You may find interesting [this post](https://instantdomainsearch.com/articles/streaming-json-jsons/)

**Comment by Mec-iS** [comment]
Merged in #144
