### ISSUE TITLE
Add Docker deployment to hydrus server

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#135]
### I'm submitting a 
- [x ] feature request.

### Current Behaviour:
A lot of users encountered importing problems for running the server or the tests

### Expected Behaviour:
server should be boxed with Docker and run with one command, with automatic provisioning. `hydrus` directory should be added to `PYTHONPATH`

### Do you want to work on this issue?
no

**Comment by palnabarun** [comment]
Shall I take this up?

**Comment by Mec-iS** [comment]
As specified and written multiple times, there is no need to claim a issue: https://github.com/HTTP-APIs/hydrus/wiki/Starting-Material

**Comment by palnabarun** [comment]
I tried to reproduce the error encountered by others. I saw that whenever the environment is setup using `python setup.py install`, there are dependency and path issues. When `hydrus` is installed with `pip install -e .`, there are no issues running the demo or the tests. One point to note is that the demo is using `gevent` which is the only thing that was needed to be installed seperately.

So,we can shift to setting up the dev environment using the editable mode of pip.

What do you say? Am I missing something here?

Also, what is meant by automatic provisioning here?

**Comment by Mec-iS** [comment]
So in your opinion we need to change the pip requirements call in `Dockerfile` with the pip editable call?

I was thinking about creating a fully featured Docker image so people can just pull the image. This would be good in the future if we are going to add Redis to the server.

Provisioning usually means building/installing system-level packages (like RDBMS or other Linux packages) to be used in the VM.

**Comment by mohdomama** [comment]
I think we should add `gevent` in `setup.py`. Its already there in `requirements.txt`. Further the problem with `python setup.py install` is that it uses `install_requires` which is only supported by `setuptools`. I believe there is already an issue for that #102 . 
I think we should have a full fledged docker image and add the root directory in `PYTHONPATH` . This will allow people to run test scripts directly rather than using `-m` flag. Also it will be nice if we setup an automatic building of docker image whenever changes are made in this repository? What do you think?
https://docs.docker.com/docker-hub/github/

**Comment by palnabarun** [comment]
@Mec-iS  Yes. But there is a caveat of using that. We need to ensure that whenever any new dependency is introduced to the project, we have to add that to `setup.py` as well as `requirements.txt`.

On a different note, I see that the project does not require `gevent`. `gevent` is only being installed to run the demo.

**Comment by palnabarun** [comment]
@mohdomama  You can run the tests directly by installing `hydrus` in editable mode with pip by `pip install -e .` to avoid the extra step of adding the root directory to `PYTHONPATH`.

**Comment by xadahiya** [comment]
@palnabarun We had a docker implementation earlier. You can build upon https://raw.githubusercontent.com/HTTP-APIs/hydrus/master/Dockerfile
Also, you should use nginx. For some reason [hydra console](https://www.markus-lanthaler.com/hydra/console/) doesn't support any other server.

**Comment by palnabarun** [comment]
Ya. I saw the dockerfile. I built the image and ran a container out from it.

One doubt I had, why did you use uwsgi? Gunicorn can also be used to run
the flask app right?

And what was the reason for choosing that very base image?

**Comment by Mec-iS** [comment]
> One doubt I had, why did you use uwsgi? Gunicorn can also be used to run
the flask app right?

we are not into addressing production/performance issues in this phase, so the simplest solution is the best

> And what was the reason for choosing that very base image?

Again having the simplest and cleanest environment is the best place to start

**Comment by xadahiya** [comment]
>  And what was the reason for choosing that very base image?

As I told you earlier, for some reason Hydra console doesn't work with anything except servers deployed with nginx. This was the primary reason for using this image as the hydra console makes debugging and understanding how the whole hydra and server part fits together a lot easier. 

Feel free to use a clean image and configure things from scratch.
