### ISSUE TITLE
Demonstration with Dynamic API paths

### ISSUE THREAD

**Issue by IamRaviTejaG** [HTTP-APIs/hydrus#137]
As listed on the ideas page (idea no. 2.4), does this need to be implemented in JS or in Python? I believe for APIs, using NodeJS would be better. How do we get started with this?

Elaboration on this idea would be appreciated.

### Do you want to work on this issue?
Yes

**Comment by IamRaviTejaG** [comment]
@Mec-iS @xadahiya @chrizandr Please have a look.

**Comment by xadahiya** [comment]
Hi @IamRaviTejaG , the main idea is to demonstrate how Hydrus and hydra draft can be used to avoid using hardcoded clients. The clearer we can demonstrate this, the faster user adoption will grow for Hydrus and [Hydra draft](https://www.hydra-cg.com/spec/latest/core/#). Last year we used [hydra-flock-demo](https://github.com/HTTP-APIs/hydra-flock-demo/) to demonstrate this behavior but things got a little messy as a lot of requests were being exchanged each second and it was very difficult for new users to understand how different drones were interacting with each other and the central controller.

We used [hydra-py](https://github.com/pchampin/hydra-py) by @pchampin  and [hydrus](https://github.com/HTTP-APIs/hydrus/) to achieve the required behavior. See 
- [Hydra flock controller mechanics](https://github.com/HTTP-APIs/hydra-flock-central-controller/tree/master/flock_controller/mechanics)
- [Hydra flock drone mechanics](https://github.com/HTTP-APIs/hydra-flock-drone/tree/master/flock_drone/mechanics)
- [Hydra flock demo](https://github.com/HTTP-APIs/hydra-flock-demo/)

> does this need to be implemented in JS or in Python?

It needs to implemented using hydrus.

@Mec-iS  You want to add anything?

**Comment by IamRaviTejaG** [comment]
Does this project need to use some sort of Natural Language Processing modules for understanding what the query actually is, and then interpret into machine level Hydra mode of communication?!

**Comment by IamRaviTejaG** [comment]
@Mec-iS @xadahiya Should this be made something similar to GitHub search? GitHub search uses something like `is:open author:IamRaviTejaG`, etc format for searching. Similar system can be developed which will then pass the query into API appropriately and the data will be output accordingly. The user then doesn't need to understand the whole API structure.

**Comment by Mec-iS** [comment]
I think this task is more about the question: how do we change APIs semantics or endpoints path or anything else in the server without modifying code?
So the idea is to design a procedure that allows the API developer to change the structure of his/her API (endpoints, path, response bodies, etc) by changing the `ApiDocumentation` without touching anything else in the server.

**Comment by Mec-iS** [comment]
As I said above, one of the most interesting feature about using Hydra is the fact that the server can change endpoints semantics without any need to hard-code the client. So we are looking for a way to demonstrate this feature using flock-demo.
Somehow should be possible from the UI to update the controller's vocabulary and change the endpoints, so to show on the screen that the drones just adapt to the new vocabulary.

**Comment by Mec-iS** [comment]
this looks good.

you can create the relative issues in the respective flock-demo repositories so we can discuss each one with more details.

**Comment by Mec-iS** [comment]
Moved to flock-demo. See referenced issues ^
