### ISSUE TITLE
Incomplete authentication test suite

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#140]
### I'm submitting a 
- [X] bug report.
- [X] feature request.

### Current Behaviour:

Authentication tests need to be updated. Current tests only test `/+ API_NAME`, rest everything needs to be tested as well.
### Expected Behaviour:

Tests should check the authentication part thoroughly.

### Steps to reproduce:

See `hydrus/hydrus/tests/test_auth.py`.
### Do you want to work on this issue?

NO

**Comment by vaibhavchellani** [comment]
@xadahiya i would like to work on this . I will try to submit a PR asap . Any points/tips you would like to offer ?

**Comment by xadahiya** [comment]
@vaibhavchellani  Sure! First, try using the Hydrus server in your browser. There are certain endpoints     (**Collection endpoints**) that need users to log in before they can be accessed.

See this
![sketch 45](https://user-images.githubusercontent.com/9114274/36748665-8debf210-1c1e-11e8-9f08-7a750fe2f7e8.png)

You should try to test different behaviors like what happens when some unauthorized user visits a collection endpoint. 
Think of different scenarios for various types of endpoints and write tests.

**Comment by tibi77** [comment]
Maybe if we do not show the endpoints. We can create a specific file (for example http://localhost:8080/serverapi/endPoints) which can be password protected. I think that it will be safer.

Right now: If someone who is not authorized tries to login the server responds with:
```
{
  "message": "The User with ID <user_id> is not a valid/defined User"
} 
```
I have found this checklist[1]. Should i implement the checks that are there?
Also the pentest part in [2] is interesting.
PS: I am asking because i am not sure what behavior you are expecting.

[1] https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Validate_content_types
[2] https://www.owasp.org/index.php/REST_Assessment_Cheat_Sheet

**Comment by chirag-jn** [comment]
I have added test cases for invalid id and invalid password by changing the id and password in the test cases from default "1" and "test" respectively.

**Comment by xadahiya** [comment]
We still need tests to check how hydrus responds when unauthorized users visit different server endpoints like collection endpoints (For example `/serverapi/DroneCollection/1`).

**Comment by tibi77** [comment]
Right now it hydrus is associating my ip(or other token of some sorts) with my ip and pass. Wouldn't it be better to ask for authentication every time we try to connect?
Also I think i can do the different users endpoints thing :smiley:.

**Comment by chirag-jn** [comment]
@xadahiya, please tell that testing for only one endpoint is sufficient, or we have to check for multiple?

**Comment by xadahiya** [comment]
@chirag-jn  you can divide the endpoints into categories like Collection endpoints, Entprypoint, Context endpoints and Data endpoints (where the actual data lives for example `/serverapi/DroneCollection/1`). Then write tests for each category.

**Comment by chirag-jn** [comment]
Oh Okay

**Comment by chirag-jn** [comment]
@xadahiya, if I am not wrong, the tests remain the same for all endpoints, it's just that the URL inside self.client.get() changes?

**Comment by Mec-iS** [comment]
About authentication and token-based authorization see also #123
