### ISSUE TITLE
Open API to Hydra Parser

### ISSUE THREAD

**Issue by suryatejreddy** [HTTP-APIs/hydrus#149]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

To implement this, we can use existing Hydrus classes to create objects from the Open API doc. The following workflow was recommended by @Mec-iS . 
OpenAPI YAML -> hydrus classes -> HYDRA ApiDoc
I am currently working on porting the basic HYDRA functionalities (GET, PUT, POST methods; classes, collections)

More suggestions are welcome.

### Do you want to work on this issue?

yes

**Comment by Mec-iS** [comment]
NOTE: In the beginning it is possible to start with a Hydra ApiDoc >> OpenAPI parser if it is an easier way

**Comment by suryatejreddy** [comment]
@Mec-iS could you elaborate on the Hydra ApiDoc >> OpenAPI parser. So you want to implement a parser that converts a Hydra ApiDoc to an OpenAPI.

**Comment by Mec-iS** [comment]
Probably it is too difficult for now to code a parser OpenAPI->ApiDoc. Instead doing an ApiDoc->OpenAPI one may be doable.

**Comment by suryatejreddy** [comment]
Okay. Any suggestions on how to start? @Mec-iS

**Comment by Mec-iS** [comment]
Exactly.

`hydrus` is already a parser from JSON-LD (HydraClasses) to Python classes. From these Python classes it is needed to create an OpenAPI-compliant document (as JSON or YAML file).

**Comment by suryatejreddy** [comment]
A get request on `/serverapi/dummyClassCollection` returns the following json

```json
{
  "@context": "/serverapi/contexts/dummyClassCollection.jsonld", 
  "@id": "/serverapi/dummyClassCollection/", 
  "@type": "dummyClassCollection", 
  "members": [
    {
      "@id": "/serverapi/dummyClassCollection/1", 
      "@type": "dummyClass"
    }
  ]
}
```
However, there is no way to access the `dummyClass` object. Because `/serverapi/dummyClassCollection/1` returns the following error. 

```json
{
"message": "The method is not allowed for the requested URL."
}
```
Shouldn't the first get method return a list of `dummyClassColelction` items with the respective properties? 
Or is there something i am missing out on? @Mec-iS 

I am trying to convert the `Collection` endpoints to OpenAPI path objects and then develop a web interface for hydrus where users can edit the HydraAPI and make changes just like swagger hub.

**Comment by chrizandr** [comment]
Actually this was done to make the server similar to Markus's issues API. You can check it out on his website. You could return IDs to access each instance separately or give a list of instances, both are possible but we went ahead with the former. 

As for the error message, better if you open an issue about it.

**Comment by Mec-iS** [comment]
@suryatejreddy The reason for an Hyperlinked API (API supporting Hypermedia) is that some of the endpoints can return links to other resources instead of plain data. Collections as you have described them are implemented to return only hypermedia, leaving to the client the possibility of going and fetching the full object with the properties.

**Comment by vaibhavchellani** [comment]
@Mec-iS the Open Api documentation that has to be imported and converted to Hydra API documentation has to be given in YAML/JSON or both ? What would be the best approach ?

**Comment by Mec-iS** [comment]
This is not a big difference as YAML can be easily re-serialized into JSON. Start with JSON that is closer to JSON-LD.

**Comment by chrizandr** [comment]
Added to #193
