### ISSUE TITLE
Update Readme.md by adding virtualenv

### ISSUE THREAD

**Issue by Himanshi-Khandelwal** [HTTP-APIs/hydrus#156]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Currently , there is no virtual environment present which lead to the installation of the packages system-wide.

### Expected Behaviour:

If virtual environment present , then the Python packages which are required in the project will be stored in a virtual environment localized to our project.
### Steps to reproduce:

Steps to do this will be updated in Readme file.
### Do you want to work on this issue?

yes

**Comment by Mec-iS** [comment]
You are right about virtual environments, everything should use a dedicated environment.
 
hydrus is supposed to be run using Docker. Docker is already a containerization tool that provides isolation of the environment from the system on top of which is running. If the user wants to use Python virtualenv is free to do it, but I don;t think it should be added in the README as it is only one of the very many others way of running hydrus.

There are a lot of work to do in the [WIKI](https://github.com/HTTP-APIs/hydra-ecosystem-wiki), we can have a new page titled "Installation" in which you can add instructions for different ways of running hydrus.
