### ISSUE TITLE
Implementing GUI

### ISSUE THREAD

**Issue by przdev** [HTTP-APIs/hydrus#158]
### I'm submitting a 
- [x] feature request.

### Current Behaviour:
hydrus doesn't have GUI that user can easily setup server

### Expected Behaviour:
With hydrus GUI user can easily setup server with executable file like exe.

### Steps to reproduce:
With useage of Tkinter or other library we can provide GUI.

### Do you want to work on this issue?
yes

**Comment by Mec-iS** [comment]
I think this could be a good idea but using a Web-based UI, there are other ideas about creating a debugging GUI for authentication in #144. Please elaborate your idea in the chat rooms by following [the guidelines](https://github.com/HTTP-APIs/hydra-ecosystem-wiki/blob/master/Starting-Material.md).

**Comment by przdev** [comment]
@Mec-iS I understand #144 but it's not same as i think. I want to make it like [this](https://a.fsdn.com/con/app/proj/xampp/screenshots/Screen%20Shot%202016-02-19%20at%2016.png/1).
This enable users to setup server without any command line or python programming.

**Comment by Mec-iS** [comment]
You should write a proposal and submitting it. Including your idea in the proposal along with others in the Ideas Page. Every student can submit up to three proposals. Having a panel from which startup Docker machines to serve hydrus agents can be interesting.

Please comment @chrizandr @xadahiya

**Comment by xadahiya** [comment]
I don't think implementing a GUI for server deployment is that important as it's already pretty easy. Also, it'll be a lot less flexible in terms of deployment options like gevent, wsgi, nginx etc.

One other interesting thing that can be done using GUI is using it to help setting up the hydra vocabulary to customise the API structure and it's endpoints.

There are two things that can be done here -
1. Create a GUI to help users set up vocabulary. Users use the GUI to describe the API structure and the GUI then spits out a hydra vocabulary file which can then be used to setup hydrus.

2. The other thing that can be done is use the GUI to load already created vocabularies and visualise it. Allowing the users to easily modify and play with the API structure that the vocabulary will create.

See these links for more info
https://github.com/HTTP-APIs/hydrus/blob/master/hydrus/hydraspec/doc_maker.py
https://github.com/HTTP-APIs/hydrus/blob/master/hydrus/hydraspec/doc_writer.py
https://github.com/HTTP-APIs/hydrus/blob/master/hydrus/hydraspec/doc_writer_sample.py

**Comment by przdev** [comment]
thanks for comment @Mec-iS @xadahiya .
I'll definitely do above two things with panel.

**Comment by Mec-iS** [comment]
> Create a GUI to help users set up vocabulary. Users use the GUI to describe the API structure and the GUI then spits out a hydra vocabulary file which can then be used to setup hydrus.

This is cool. I know there are really complex RDF-specific editors around, but having one for HYDRA vocabulary would be great. This would also improve our understanding about parsing JSON-LD. 
Possibly it should start with representing the JSON-LD as a tree (that is a particular type of graphs). I remember [this application/service for building interactively knowledge maps](https://rainbird.ai) trying to create a UI to make people building their knowledge graphs using nodes (circles) and edges (arrows).

**Comment by Mec-iS** [comment]
NOTE: I think this should be implemented in https://github.com/HTTP-APIs/python-hydra-agent
This way we can have a vocabulary-building plus testing environment in one tool.

**Comment by vaibhavchellani** [comment]
@Mec-iS  i find this idea very interesting , i was working on qgis but qgis3 is not available for OSX currently so have to wait till released (building from source is a huge pain). Can you please elaborate on what is expected from this ? and if you could suggest some resources that would be great !

**Comment by Mec-iS** [comment]
Let's move the discussion to https://github.com/HTTP-APIs/python-hydra-agent
Open a issue there please.
