### ISSUE TITLE
Changes Log

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#159]
### I'm submitting a 
- [X] bug report.

### Current Behaviour:
We do not have a CHANGES_LOG.txt file

### Expected Behaviour:
According to MIT License compliance suggestions, the repository should have a CHANGES LOG file in the root

**Comment by suryatejreddy** [comment]
What type of change_log should be generated? A very simple one could be `git log --oneline --decorate`, which would provide line by line history of commits and merges. Is this sufficient?

**Comment by Mec-iS** [comment]
This is a nice start but going commit-by-commit could be too much. The output of git log should be grouped into features with short explanations. See [here](https://github.com/olivierlacan/keep-a-changelog) or other examples in other repositories.

**Comment by suryatejreddy** [comment]
Yes, I agree with you. What are your views on automating this? For example - https://github.com/skywinder/github-changelog-generator.

**Comment by Mec-iS** [comment]
I think we can start writing a changes log manually by aggregating commits into features. And then when we are going to use releases, every release's merge-message will contain the features that will be added to the changes log. 

I think first we may need a template for merge messages also.

**Comment by IamRaviTejaG** [comment]
@Mec-iS Do you mean a specific template for commit messages? If it is so, it can be of 3 parts:
1. Shortlog. (Max. 50 characters)
2. Commit body. (Max. 72 characters) (Not mandatory, but recommended).
3. Issue reference. (Use of fixes/closes word denoting if the commit fixes a bug or adds a feature).

Example:
```Git
cli.py: Changed CLI options

Changed the CLI options "--authentication" to "--auth/--no-auth"

Fixes https://github.com/HTTP-APIs/hydrus/issues/159
```

**Comment by Mec-iS** [comment]
I mean **a template for Pull Requests**. So when they are merged changes log is the body of the PR message.

**Comment by ashwani99** [comment]
@Mec-iS There is already a template for PRs https://github.com/HTTP-APIs/hydrus/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Also, don't you think entry in changes log for every merged PR is an overhead? Can we do this every release?

**Comment by Mec-iS** [comment]
Then a solution may be to add to the PR template a section changes log where the major features/fixes of the PR have to be listed. So at release time we can can just copy and paste into the changes log file the most relevant features/fixes added by each PR. For the PR that have small fixes or less relevant, we just don't add them to the file.

**Comment by ashwani99** [comment]
@Mec-iS That would be better. Then it's easier to manually update the change log. I will go ahead and add the section in the PR template

**Comment by Mec-iS** [comment]
From now on, at every release the most relevant features in the PRs' messages have to be collected into a `CHANGELOG.txt` file
