### ISSUE TITLE
Add option to add database and server url in CLI

### ISSUE THREAD

**Issue by vddesai1998** [HTTP-APIs/hydrus#160]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

If we want to use a database file instead of using sqlite in memory database we can not give it as database url through cli.

### Expected Behaviour:

User will be able to give database and server url as argument in hydrus CLI
### Do you want to work on this issue?

Yes

**Comment by xadahiya** [comment]
Fixed with #161
