### ISSUE TITLE
Differences in cli.py and main.py

### ISSUE THREAD

**Issue by IamRaviTejaG** [HTTP-APIs/hydrus#165]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:
Currently, the files `cli.py` and `main.py` are independent and any changes made in the main.py file are not reflected back into the CLI interface. This way, the CLI runs an older version of the code.

### Expected Behaviour:
The CLI is expected to run always the latest version of the code, which will be possible only when the `main.py` and `cli.py` are somehow merged.

### Do you want to work on this issue?
Yes

**Comment by Mec-iS** [comment]
My general opinion is that if the CLI is using some code from the `main.py`, it should just load the code that is needed. For sure we don't want to have replicated code, but we also want segregation of concerns between basic functionalities and the CLI, that is an interface that access these functionalities. Interfaces shall be always something that are pluggable on-top of existing functionalities. Mixing the two things is a design flaw.

**Comment by xadahiya** [comment]
Fixed with #166
