### ISSUE TITLE
requirements.txt is missing in develop branch

### ISSUE THREAD

**Issue by ashwani99** [HTTP-APIs/hydrus#169]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:
Currently the `requirements.txt` file containing dependencies is missing in the `develop` branch. The dependencies are hardcoded inside setup.py file. There is a better way to list the dependencies inside requirements.txt and read the content from the setup.py file. This way setup.py becomes cleaner.
 
### Expected Behaviour:
A file containing all the dependencies should be added `requirements.txt`

### Do you want to work on this issue?
yes

**Comment by Mec-iS** [comment]
It can be an idea to parse the dependencies into the `setup.py` file from an external `requirements.txt`. See [here](https://stackoverflow.com/a/16624700/2536357)

**Comment by ashwani99** [comment]
Closed via #171
