### ISSUE TITLE
Designing authorization policies

### ISSUE THREAD

**Issue by alohamora** [HTTP-APIs/hydrus#173]
### I'm submitting a 
- [ ] feature request.

### Current Behaviour:

Currently, the users can be registered only by the server creator using `add_user` function, so there is no option to extend the user base of the API.
### Expected Behaviour:

The users will be able to register themselves on the API using a `/serverapi/register` URL by posting their credentials and would be able to access the resources. 

### Steps to reproduce:

Introduce a `Resource` class mapping to the url `/API_NAME/register` with an allowed POST method, which shall call the already built `add_user` function to register the user.
### Do you want to work on this issue?

yes

**Comment by xadahiya** [comment]
We should discuss this first. Do we really want to provide users the ability to sign up themselves? This falls under **`1.3 More User defined Controls for the server`**. 
For example, there can be some sensitive data on our API that only registered users can see. Doing this will defeat that purpose as anyone will be able to sign up and see it.

I agree there should be a `register` endpoint but only `admins` or `registered users` should be allowed to add new users (this part is open to discussion).

@Mec-iS  @chrizandr  ^^

**Comment by alohamora** [comment]
@xadahiya Yes, you  are correct and this is just a starting point for the above mentioned project, as I am working on `Role based access control` methods for the GSOC proposal, so this will evolve in a admin and user based authentication where admin shall decide the role and access limits of the user.
So I am planning to work on improving this as per the specifications you provided  in the coming days.

**Comment by Mec-iS** [comment]
I see some misunderstanding in the scope and the scenarios that hydrus has to tackle.

Please always consider that the "users" of the API we are talking about when speaking of Hydra are automated clients. Hydra is primarily a technology to make automated agents to exchange data, so everything in hydrus should be designed with this as primary constraint.
"Users" (aka other machines in the same APIs network) would be registered at deploy time. Nobody should be allowed to register dynamically as it would be a security flaw in the network.
The "User Defined Controls" task is in the same scope: having a list of machines allowed in the network, which machines are allowed to access which endpoints?

Please always refer to the domain we are tackling. Hydra is not a front-end or business-to-consumer technology; all the needs of this kind have to be addressed by other layers beyond the "API network layer" we are working on at this moment.

Briefly, Hydra's developer/engineers that wants to build an infrastructure/architecture are our "customers", not the final users/clients that needs to access the data. Providing a front-end (in the sense of a layer facing external end-users) is part of the general layout of the infrastructure that is up to the engineers to decide and implement (maybe using hydrus itself, but it is something that is outside of the reach of the tools we are developing).

**Comment by xadahiya** [comment]
Thanks for the clarification @Mec-iS

**Comment by alohamora** [comment]
Thank you for the clarification @Mec-iS 
So for the project regarding `Adding user based controls` for the user does the hydrus server wish to incorporate a `Role based access control` system where the access control of the customers can be dynamically modified by the admins of the hydrus server.

**Comment by Mec-iS** [comment]
> So for the project regarding Adding user based controls for the user does the hydrus server wish to incorporate a Role based access control system where the access control of the customers can be dynamically modified by the admins of the hydrus server.

Yeah, but remember there are no customers in Hydra, **consumers** of the data served by hydrus are automated clients in a network of servers/APIs. This modifications you talk about can take place only through "super-user" control on the infrastructure (like changing configurations in the containers or through changing the ApiDoc; Hydra-core vocabulary does not define by-design authorization features). The idea is to define a Linux-like authorization system to define (nested) layers of access for different machines at deploy-time or, possibly, on-the-fly without redeploying the interested machines. I think studying how LDAP works be of some help.

**Comment by alohamora** [comment]
@Mec-iS  @xadahiya  I have created a basic layout for authorization with the API using the `OAuth` framework design. Here is the class diagram of the same:

![document 1](https://user-images.githubusercontent.com/30872134/37324124-a8f29c14-26ad-11e8-81cb-2460721c00fb.jpg)

Basic properties of the system
- The clients/users registered will be registered with the API at the time of deployment.
- The applications/automated agents i.e. the end users of the API shall authorize with the API under the account of a pre-registered client.
- There can be only fixed no of applications associated with a single client.
- The application shall inherit the access levels of the client as decided by the **super-user** admin.  

This is a basic layout for authenticating which shall ensure a fixed no of applications using the API
and there shall be minimal password sharing between the application and the API.

NOTE - Currently I have allowed dynamic authorization for an application as the applications associated with a client may be dynamic in nature. Please comment whether this is correct or do we have to register each application or agent as a seperate user on the API.
Source - [Google API OAuth authentication](https://developers.google.com/identity/protocols/OAuth2)

**Comment by Mec-iS** [comment]
For "Client" in the picture you mean some kind of monitoring/testing/querying Web-Javascript UI?

Please be more specific with definitions. This is a use-case that should clarify, we have these sets of agents in the network we are trying to build:
* user A deploys 1 (or a generic number N) `hydrus` machine(s) (hydrus machines are both Hydra clients and servers). The elements in this network are defined at start-up;
* user A has also a Web UI client to monitor/test his/her network (`hydra-agent`), this client can use a federated login (like a Gmail or Github account) to log into the server(s) in the network as he/she is the "super-user". His/her email is defined at runtime in a configuration module, together with the database credentials; like it happens for Django administrators for example;
* some external user B wants to connect to an API in the user A's network with a generic Hydra client, user B has a username and a password issued by user A to connect to a given machine to request the data. User B, to connect to the machine's API, has to go through the 2-Factor Auth already developed in `hydrus`

**Comment by alohamora** [comment]
@Mec-iS 
The `client` in the above picture corresponds to the `user A` as you specified and the `Automated agents` shall be the external users which shall have to authenticate using `OAuth`.
Please correct me if I am wrong.
Also I have started to build a proposal on this...so please suggest me any other specifications regarding the nature of authentication or level of control.
a doubt - Can there be more than one super-user for a network?

**Comment by Mec-iS** [comment]
> Can the external users be registered on the fly or at the startup??

New user and credentials can only be added by somebody that has super-user privileges.

> Can there be multiple super-users for a network??

For now this makes things too complicated in terms of concurrent access, but in general it is a good practice to have two super-users to lower the possibility of locking out because of compromised keys.

> Currently my use-case defines access controls for the external users and the client inherits the access limits, should the access limits be defined separately for the clients also??

For external users (user B), the user is the client, I don't understand this distinction. User B access the needed data according to the privileges assigned using Hydra client and credentials.

**Comment by Mec-iS** [comment]
> The distinction is in the fact that an external user that is registered on the network can create one or many hydra clients to access data from the API.

As I have already specified, the super-user is the only allowed to create client credentials.

> e.g In the google API a user has to get client id and client secret to use API data in a client application and then the client (application/client API) makes the request for data from the server by obtaining access token from the server.

As I have already stated above, we are not developing end-user APIs, this is beyond the scope of the task. The external client's credentials are credentials generated by a super-user for one client not for a human-user. The fact that a human-user may have different clients is not relevant at the moment, the superuser will just generate more clients. It is something that complicates only the scenario. Please do not use Oauth2 if this makes things too complicated for you, use the custom 2-Factor authentication for both internal and external. Keep in mind and in the design the distinction though, between credentials generated for internal use of the super-user and the one that are made for external clients (that will probably need more security added in the future).

**Comment by alohamora** [comment]
@Mec-iS 
Thanks for clearing that out...will keep in mind from now.
Also I am preparing a proposal for `Adding user based controls` and I wish to also incorporate authentication using OAuth in that, so if you can give any suggestions or any specifications for the same...it would be really helpful.
Thanks in advance...!!
