### ISSUE TITLE
Querying: Linked Data Fragments

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#174]
### I'm submitting a 
- [X] feature request.

### Current Behaviour:
hydrus has no support for : 
* [Linked Data Fragments](http://www.hydra-cg.com/spec/latest/linked-data-fragments/)
* [Triple Pattern Fragments](http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/)

hydra-cg.com states:
> Linked Data Fragments:
API and client designs to publish and query Linked Data at Web-scale
Get familiar with Linked Data Fragments or read the triple pattern fragments specification
[Various LDF data sources](http://data.linkeddatafragments.org/) are already available. [Query them](http://client.linkeddatafragments.org/).

Notes:
* see the concept of _selector_: 
> A selector is a boolean function that decides whether or not a certain triple (or graph of triples) belongs to a part of a dataset.
* hydrus can become a [Linked Data Fragments server](http://www.hydra-cg.com/spec/latest/linked-data-fragments/#linked-data-fragments-servers)? How?

### Expected Behaviour:
Triple Pattern Fragments are part of the Hydra specification. When and how should we implement them? It probably should be the right way to go to implement querying on the API.

[UPDATE] Implementation of Fragments have been moved to https://github.com/HTTP-APIs/python-hydra-agent/issues/3
This issue is about TPF only. How can we make `hydrus` a TPF-query enabled server?

**Comment by Mec-iS** [comment]
**NOTE:** General overview for the architecture for the TPF querying feature:
1. The client represents the subsets as a TPF `? ? someObject`
2. The client passes the query to the server in a server-understandable format, that can be: http://localhost/api/someClass/tpf?s=query?p=query?o=someObject
3. The server parse the fragment into its internal querying language, that can be CYPHER for Redis Lib or any other depending on the database supported
4. The server responds with a JSON-LD of the requests subset of the dataset

**Comment by vddesai1998** [comment]
>The client passes the query to the server in a server-understandable format, that can be: http://localhost/api/someClass/tpf?s=query?p=query?o=someObject

What kind of effect someClass will have on the query?
Can't it be http://localhost/api/tpf?s=query?p=query?o=someObject
to expose the whole dataset?

**Comment by Mec-iS** [comment]
This has been moved to https://github.com/HTTP-APIs/python-hydra-agent/issues/3
