### ISSUE TITLE
Retrieving specific subsections of an object

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#175]
### I'm submitting a 
- [X] feature request.

### Expected Behaviour:
Should be possible to retrieve parts of an object or objects by using an endpoint like `http://localhost/api/drone/1#speed`, in this case the API should return something like:
```
{
  "@id": ".../drone/1",
  "@type": "...Drone",
  "drone:speed": 35
}
```

**Comment by py-ranoid** [comment]
Could we use URL-encoded parameters instead ? 
Something like `http://localhost/api/drone/1?attr=speed`

Because according to this [answer](https://stackoverflow.com/questions/18752995/how-to-get-access-to-the-url-segments-after-a-in-python-flask)
> As such, flask drops everything after the '#'. If you want to forward these to the server, you'll have to extract them on the client and pass them to the server via a query parameter or part of the URL path.

**Comment by Mec-iS** [comment]
In fact fragments are a client-side feature according to RFC. So should be up to the Hydra client (hydra-agent) to map `#speed` to `?attr=speed` when dereferencing and the opposite for hydrus when referencing. But it is something that we should keep for later.

This is a part of the client-server protocol so we should remember that when designing the client. The [current client](https://github.com/pchampin/hydra-py/tree/master/lib/hydra) we are using and that we should improve does not consider this feature.

**Comment by Mec-iS** [comment]
Moved to https://github.com/HTTP-APIs/python-hydra-agent/issues/3
