### ISSUE TITLE
Expired token should be removed from the database

### ISSUE THREAD

**Issue by anubhav253** [HTTP-APIs/hydrus#178]
### I'm submitting a 
- [x] bug report.

### Current Behavior:
We are storing the token in our database which get expire after 45mins. With this expiration the token should also be removed from the database. As it will unnecessarily increase the size of database.

https://github.com/HTTP-APIs/hydrus/blob/a13f3d0a5cc1d2e62bb0c5e2d67705f962b6ad5c/hydrus/data/user.py#L88

### Expected Behavior:
We should have removed the token once its expired and we get a call with this token(But this one is not a full proof  as sometimes it might not be possible that we don't get a call that token). 
So here i would like to use redis which is commonly used for storing access-token with some expiration time. Which will also improve the efficiency of authenticated api because of its being faster that SQL.

### Steps to reproduce:
We can check the database as the key are not being removed.

### Do you want to work on this issue?

yes

**Comment by ashwani99** [comment]
I want to add a tiny point to this. Please consider changing the variable name https://github.com/HTTP-APIs/hydrus/blob/a13f3d0a5cc1d2e62bb0c5e2d67705f962b6ad5c/hydrus/data/user.py#L87
The variable name is ambiguous, as it calculates a `timedelta` but it is named as `present`.

**Comment by anubhav253** [comment]
@ashwani99 - yeah sure will consider that changes as the name _present_ isn't appropriate here.

**Comment by alohamora** [comment]
@ashwani99 Thanks for pointing that out

**Comment by anubhav253** [comment]
@alohamora - yeah i think we should use redis here for storing the token. your opinion ?

**Comment by alohamora** [comment]
@anubhav253   Actually I dont know much about redis so I cannot comment on that for now.
As far for deleting the records using sqlalchemy I think we need to run a `cron` job scheduled to run each min to delete records.
Also as per the user model suggested by @Mec-iS  there can be only a fixed no of users/clients which are designated to use the api and according to the current logic of updating the token, the no of token records cannot exceed the total no of users.
So does running a cron job be a computationally correct solution?? Or should we search solutions using redis?? 
@Mec-iS please comment on this

**Comment by Mec-iS** [comment]
Check this [blogpost](http://tecladocode.com/blog/learn-python-defining-user-access-roles-in-flask/) for hints about users management.

> As far for deleting the records using sqlalchemy I think we need to run a cron job scheduled to run each min to delete records

For now, just check for expired tokens every time the server checks a token. In pseudo-code:
```
if not token.is_valid():
    ...
expired = Token.filter(expires<time.now())
for e in expired:
    e.delete()
```
> the no of token records cannot exceed the total no of users.

There can be the corner-case in which an old token is expired and a new token is issued for the same client. The one-to-one ratio between client and token is not really relevant at the moment.

> So does running a cron job be a computationally correct solution?? 

No. And we are not considering production-level optimization. In this case a cron job is just overkilling, see solution above.

In general, create a simple SQLAlchemy model to store clients, and a simple model to store tokens with a foreign key to clients and an index on the token value column and the "expires" column, so it can be filtered faster.

Why you come up with so complicated solutions guys? We are developing an ALPHA version. Things that matter are clean design and strong design principles (especially for security).

**Comment by Mec-iS** [comment]
Merged to `develop`. Waiting for merge in `master`.
