### ISSUE TITLE
setup.py: Missing requirements

### ISSUE THREAD

**Issue by mehtavishwa30** [HTTP-APIs/hydrus#180]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
The setup.py file is missing some requirements under install_requires.

### Expected Behaviour:
The file should contain the following packages:
         gevent==1.2.2
         greenlet==0.4.12
  

### Do you want to work on this issue?
Yes

**Comment by ashwani99** [comment]
@mehtavishwa30 `gevent` is already present [here](https://github.com/HTTP-APIs/hydrus/blob/develop/requirements.txt). And we don't require `greenlet` in our current repo.

**Comment by mehtavishwa30** [comment]
@ashwani99 isn't `greenlet` among the required packages? It's in the requirements.txt file of the repo.

**Comment by ashwani99** [comment]
@mehtavishwa30 No it's not used as for the current state of development. You can also cross check it from the `develop` branch itself.

**Comment by mehtavishwa30** [comment]
@ashwani99 sure. Thanks for this.
