### ISSUE TITLE
Double requirement given: Click

### ISSUE THREAD

**Issue by Shekharrajak** [HTTP-APIs/hydrus#188]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
Double requirement given in branch `develop`: Click
2 times at [line 25]( https://github.com/HTTP-APIs/hydrus/blob/cdb72e4a4fc7e6b788387f6d2ec8422b486a1031/requirements.txt#L25) and [line 10](https://github.com/HTTP-APIs/hydrus/blob/cdb72e4a4fc7e6b788387f6d2ec8422b486a1031/requirements.txt#L10)

### Expected Behaviour:
Must be once

### Steps to reproduce:

`
pip install -r requirements.txt
`
returns =>
```
Double requirement given: Click (from -r requirements.txt (line 25)) (already in click==6.7 (from -r requirements.txt (line 10)), name='Click')
```

**Comment by xadahiya** [comment]
Fixed with #189
