### ISSUE TITLE
Implement user defined endpoints instead of class names 

### ISSUE THREAD

**Issue by vaibhavchellani** [HTTP-APIs/hydrus#201]
### I'm submitting a 
- [ ] bug report.
- [X] feature request.

### Current Behaviour:

Right now the endpoints are the same as class names which are defined by the user when defining classes  in apidoc.
### Expected Behaviour:

We will be able to defined endpoints will be user defined 

### Do you want to work on this issue?

yes

**Comment by vaibhavchellani** [comment]
@chrizandr waiting for your comment

**Comment by xadahiya** [comment]
@chrizandr ^^ this is from the discussion we had on Gitter. Can you suggest anything?

**Comment by xadahiya** [comment]
Fixed in #206
