### ISSUE TITLE
Write a parser to fetch the semantic references of simple enough classes

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#204]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

This is related to the discussion we had here https://docs.google.com/document/d/1J9PlcXUfu76lruJCb_1vKcQauL-J6H2wxZxqzdZO9dQ/edit

### Expected Behaviour:

Every class/property needs to have a semantic reference. If it's a complex object then define the object in vocab itself and provide semantic references to its properties else directly provide a semantic reference.
Either way, semantic references need to be there.

It would be better if you write a parser that'll try to find semantic references for properties from `Schema.org` and similar sources.

### Do you want to work on this issue?
NO

**Comment by vaibhavchellani** [comment]
do we actually need that ? 
OAS supports some basic data types ,we can just hardcode them and use them directly .
User defines the objects like this usually:
1. `id:
        type: integer
        format: int64`
2. `User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string`
3. `User:
    type: object
    `

3rd method is not recommended but it doesn't give any error , its ambiguous and probably the open api will face issue there too . 
If the user uses any of the methods other than 3 we dont need a schema.org parser for that .

**Comment by vaibhavchellani** [comment]
@xadahiya ^^

**Comment by xadahiya** [comment]
Of course, we do. See you can break any complex type into simpler ones and define them using `vocab:SomeObject` but for simpler properties, we need semantic references. For example in this case,
You can first define provide a reference to User as `vocab:User` but then you'll need to provide semantic references to User properties. `Id` will have reference to `https://schema.org/identifier` the same goes for other properties as well. You can use a fallback if no semantic reference is found but you need to provide semantic references.

See this for a better understanding https://github.com/HTTP-APIs/hydra-flock-drone/blob/master/flock_drone/api_docs/doc_gen.py

**Comment by vaibhavchellani** [comment]
User will give semantic references in the OAS spec if its not in the doc i think . If the class is defined in the doc then we can parse the class and props directly other wise we will use the semantic ref given by user . If we dont have either of the above then i think we may need the parser we are talking about ,but it seems a bit ambiguous as the user might have something else in mind while saying "petID" and using schemas defined on schema.org might not be what he had in mind . It is logical to go the parser way but it may change the meaning in some cases dont you think ?

**Comment by xadahiya** [comment]
>If the class is defined in the doc then we can parse the class and props directly other wise we will use the semantic ref given by user

We need to provide semantic references to these properties the user has defined for any object.

>  user might have something else in mind while saying "petID" and using schemas defined on schema.org might not be what he had in mind 

I agree with you. We can't generate everything using the parser but we need to reduce the effort needed for porting as much as we can. The user can go through the generated APIDoc and can manually update the semantic references that are not correct. This will reduce his work significantly though.

**Comment by vaibhavchellani** [comment]
yes , makes sense .
Beautiful Soup should be good enough to do the job right ?

**Comment by vaibhavchellani** [comment]
hey @xadahiya i thought parsing schema.org should do the trick , but they use their custom search engine to get the results , we could build our own search engine too but that would be too much for a simple things i think . if i google "searchString site:schema.org" gives me the same results i had on schema.org .

How should we get the semantic references according to you ?

**Comment by xadahiya** [comment]
Using placeholders for now
