### ISSUE TITLE
Add created/updated attributes for Instance model

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#216]
### I'm submitting a 
- [X] feature request.

### Expected Behaviour:
We shall be able to track creation and updating datetime of the instances for server/client sync reason.

### Solution
Add a `created` and `updated` attributes [here](https://github.com/HTTP-APIs/hydrus/blob/master/hydrus/data/db_models.py#L36) using `default` and `onupdate` SQLAlchemy ` [arguments](http://docs.sqlalchemy.org/en/latest/core/defaults.html):
```
Column('created', DateTime, default=func.now()),
# define 'last_modified' to use the current_timestamp SQL function on update
Column('last_modified', DateTime, onupdate=func.utc_timestamp())
```
There is also a way to pull the default value from a key,value table:
```
# define 'key' to pull its default from the 'keyvalues' table
Column('key', String(20), default=select([keyvalues.c.key]).where(keyvalues.c.type='type1')),
```

**Comment by invinciblycool** [comment]
Would like to work on this. Is this up for grabs?

**Comment by Mec-iS** [comment]
you can work on any issue you prefer, no need to ask. Please get familiar with Github Workflow and how to submit a Pull Request.

**Comment by Mec-iS** [comment]
This has been merged to `develop`. Waiting for merging to `master`.
