### ISSUE TITLE
Implement the checksum mechanism we discussed over mail.

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#218]

**Comment by vddesai1871** [comment]
>Implement the checksum mechanism we discussed over mail.

@Mec-iS  @xadahiya can you provide more information on this issue from the mail you are referring to.
Is it about global unique ids we were planning to implement?

**Comment by Mec-iS** [comment]
This has been moved to the agent-server data synchronisation issue #300 and relative inbox/outbox system that could or could not work leveraging checksums.
