### ISSUE TITLE
Use uuid as unique IDs to identify data in @id.

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#225]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Use python Uuid to generate unique IDs instead of the ones assigned by the database to identify data in @id.

@sandeepsajan0  please ask any doubts here. Also, you should use the `agent-uuid` branch from now on.

### Do you want to work on this issue?

No

**Comment by xadahiya** [comment]
@sandeepsajan0  have you started working on this? Let me know what doubts you had earlier

**Comment by vaibhavchellani** [comment]
fixed in #227 , closing .
