### ISSUE TITLE
Implementing readOnly, writeOnly and Required Properties 

### ISSUE THREAD

**Issue by vaibhavchellani** [HTTP-APIs/hydrus#226]
### I'm submitting a 
- [ ] bug report.
- [X] feature request.

### Current Behaviour:

Right now although the doc contains properties like readOnly ,writeOnly , Required the functionality is not implemented in Hydrus. We need to implement this functionality so that we can have checksums instead of pk's or UUID's , advantage of that would be that client can reconstruct the checksum to check what is to be fetched .
### Do you want to work on this issue?

~YES~

EDITED BY Mec-iS

**Comment by vaibhavchellani** [comment]
for checksum mech do we need to implement writeOnly and ReadOnly functionality ? @xadahiya @Mec-iS

**Comment by vddesai1998** [comment]
For requests containing a single object, the server returns 400 when the required parameter is not provided and returns 405 (Method not allowed) when a client tries to modify read-only data.
But when a client in a single request sends multiple objects to the server and one or few of them are violating this conditions should other valid objects be processed or the whole request should be discarded? If we process those valid objects, which status code and message should be returned as the response? And how the client finds out which objects it needs to send again and which are already processed?

**Comment by Mec-iS** [comment]
@vddesai1998 nice point. I suppose this is not the right issue for this. We should have a "Multiple insertion/update for list of items" issue.

This issue remains here, to implement the status code system:
* 400: missing parameter
* 404: object not present
* 405: read-only item, write-only item

**Comment by vddesai1998** [comment]
> We should have a "Multiple insertion/update for list of items" issue.

We do not have endpoint method for updating multiple items at once. Should I create an issue? ( I am asking because I do not know why it was not implemented early when we implemented multiple inserts and deletes. )

**Comment by Mec-iS** [comment]
> We do not have endpoint method for updating multiple items at once. Should I create an issue? ( I am asking because I do not know why it was not implemented early when we implemented multiple inserts and deletes. )

bedore going too far with this we should ask in the mailing list what is the general consensus about passing list of items and implementing multiple resources' CRUD operations, I suppose.

After a brief research:
> But when a client in a single request sends multiple objects to the server and one or few of them are violating this conditions should other valid objects be processed or the whole request should be discarded? 
In my opinion, in this case the handler should return `202 Accepted` instead of `201 Created`. Maybe in the body of the response should be present the item that failed and at which constraint it failed.

**Comment by vddesai1998** [comment]
> In my opinion, in this case the handler should return 202 Accepted instead of 201 Created. Maybe in the body of the response should be present the item that failed and at which constraint it failed.

This solves my all doubts about proper way to check for contraints. Can you assign this issue to me..?

**Comment by Mec-iS** [comment]
@vddesai1871 if this is fixed, please reference PR number.

**Comment by vddesai1871** [comment]
@Mec-iS I haven't created a PR yet, I have yet to write code for write-only properties so I will complete it and open a PR over the weekend.

**Comment by aribalam** [comment]
@Mec-iS @xadahiya what is the status of this issue? I would like to create a PR for this. Would it be fine if I submit it by the weekend?

**Comment by Mec-iS** [comment]
@aribalam there is already a PR #326 it would be nice to widen the collaboration and take the best part of both

**Comment by vddesai1871** [comment]
Both PRs are still using api doc in crud.py, #326  is using it to handle write-only props and #345 is using it for required props, as I mentioned earlier by only storing write-only attribute in database we can still handle read-only and required from resources.py without making any unnecessery database reads (I think storing required attribute in db, we will need to change the database schema and we might need multiple databases reads per request to handle required property constraint). By not storing required attribute in db and checking for it in resources.py we will be able to check for all constraints without passing api doc in crud.py. And we can use the approach I mentioned in this https://github.com/HTTP-APIs/hydrus/pull/326#issuecomment-453019013 to handle issue with path of nested objects.  @aribalam @xadahiya any ideas....?

**Comment by aribalam** [comment]
> we can still handle read-only and required from resources.py without making any unnecessery database reads

@vddesai1871 We can definitely handle read-only and required properties without storing it in the database. But it would be much cleaner and maintainable if we do it the other way. I think logically,  checking property constraints should be handled on a lower level (i.e. `crud.py`) than `resources.py`. We might need to add more resources in the future and it could become a tedious task if we do it the above way. According to me, it would be better to check for all property constraints at one place for easilibility in maintaining and debugging code.

> I think storing required attribute in db, we will need to change the database schema and we might need multiple databases reads per request to handle required property constraint

I dont think so. The database is read when the following code gets executed.
`prop = session.query(properties).filter(properties.id == data.predicate).one()`
This has to be present anyway. I am just adding a few columns which wont make that much of a difference. Correct me if I am wrong.

As far as ApiDoc is concerned, `crud.py` should not use it at all. Although i had to use it for checking required props as i could not think of doing it without passing the doc from `resources.py` (and without using `resources.py` for handling property constraints). We might need to discuss about this.

**Comment by vddesai1871** [comment]
>@vddesai1871 We can definitely handle read-only and required properties without storing it in the database. But it would be much cleaner and maintainable if we do it the other way. I think logically, checking property constraints should be handled on a lower level (i.e. crud.py) than resources.py. We might need to add more resources in the future and it could become a tedious task if we do it the above way. According to me, it would be better to check for all property constraints at one place for easilibility in maintaining and debugging code.

:+1: 

>I don't think so. The database is read when the following code gets executed.
prop = session.query(properties).filter(properties.id == data.predicate).one()
This is used only once in both the cases and has to be present anyway.

I was talking about handling required property constraint, and it will also require changing db schema if I am not missing something. Can we do it without changing db schema?

@xadahiya  we are thinking to go with storing these attributes in db, but we will probably need to change db schema to handle required property constraint( because to check for required properties we must know which properties belongs to the class of object we are trying to insert, and if I am correct we can't do that in current db schema)
1) we can add class_id field in `BaseProperty`  but a property might belong to more than one class, so it won't work.
2) We can create a new table mapping class_ids and property_ids....

@xadahiya @Mec-iS @chrizandr  Any suggestions... ( We can't move forward with this feature without solving this problem)

**Comment by aribalam** [comment]
> We can create a new table mapping class_ids and property_ids.

This might be a good way to go.

**Comment by Mec-iS** [comment]
A change in database schema is not a big deal, if we implement a migration tool (Alembic:  I open a issue for that).

> checking property constraints should be handled on a lower level (i.e. crud.py)
:+1:

**Comment by Mec-iS** [comment]
@aribalam please contribute to https://github.com/HTTP-APIs/hydrus/pull/326 on branch https://github.com/vddesai1871/hydrus/tree/impl_props

**Comment by vddesai1871** [comment]
@Mec-iS the best thing about hydrus is its DB schema, I don't think we will need migration. 
Regarding to this issue the approach suggested by @chrizandr here https://github.com/HTTP-APIs/hydrus/pull/326#issuecomment-459416953 will provide a more cleaner solution and it will also provide a more elegant solution for #327. I think https://github.com/HTTP-APIs/hydrus/pull/326#issuecomment-459416953 is the way to go...

**Comment by Mec-iS** [comment]
Merging at https://github.com/HTTP-APIs/hydrus/pull/326

**Comment by Mec-iS** [comment]
Migrations implementation at https://github.com/HTTP-APIs/hydrus/issues/349

**Comment by Mec-iS** [comment]
Any of the readOnly, writeOnly and Required properties as defined in the ApiDoc, shall be treated as per these plan:
* for now all these properties shall be checked via functions (i.e. `check_write_only` in case of a GET, `check_read_only` in case of a POST, etc.)
