### ISSUE TITLE
Add Exceptions and error handling for parser 

### ISSUE THREAD

**Issue by vaibhavchellani** [HTTP-APIs/hydrus#230]
### I'm submitting a 
- [ ] bug report.
- [X] feature request.

### Current Behaviour:

Right now the parser parses the Open api documentatin as is , if the api documentation has syntactical errors , they are ignored .Also if a specific thing cant be done in hydrus it should be pointed out so that user can change it .
### Expected Behaviour:

Errors in Open Api doc provided should be pointed out and should be handled gracefully by the parser. Places where the open api doc has to be made hydrus compatible will be printed out .

### Do you want to work on this issue?

YES

**Comment by xadahiya** [comment]
@vaibhavchellani  Is this fixed?

**Comment by vaibhavchellani** [comment]
No I haven't started working on it yet , working on implementing required property

**Comment by vaibhavchellani** [comment]
fixed in #262
