### ISSUE TITLE
Warning while running 1 test

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#235]
### I'm submitting a 
- [x] bug report.

### Current Behaviour:
Getting this warning while running tests on hydrus. 
![selection_079](https://user-images.githubusercontent.com/9114274/42487553-1adeaf9c-841f-11e8-9878-7424e374d59b.png)

### Expected Behaviour:

There should be no warnings
### Steps to reproduce:

Run tests using `python -m unittest` in hydrus tests directory.
### Do you want to work on this issue?

NO

**Comment by vaibhavchellani** [comment]
i have fixed the warning in PR #250

**Comment by vaibhavchellani** [comment]
i think we can close this @xadahiya
