### ISSUE TITLE
Incorrect urls from parser generated doc

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#237]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

All the Urls generated from the parser doc have incorrect urls.
![selection_080](https://user-images.githubusercontent.com/9114274/42488262-4bd6ebfc-8422-11e8-8650-1f2129f9ee05.png)

### Expected Behaviour:

Urls should be correct
### Steps to reproduce:

Run hydrus using the parser generated doc
### Do you want to work on this issue?

NO

**Comment by xadahiya** [comment]
@vaibhavchellani  Did you even try running hydrus using the parser? There are a lot of errors

**Comment by vaibhavchellani** [comment]
@xadahiya yes but after the PR was merged , i have already made changes and corrections but did not create a PR coz of second deadline

**Comment by vaibhavchellani** [comment]
fixed #241
