### ISSUE TITLE
Extra paths in entrypoint

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#238]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

There are several extra paths in the entrypoint. For example `Order`, `Pet` and `User` should not be there.
See this 
![selection_080](https://user-images.githubusercontent.com/9114274/42488343-b0b28a04-8422-11e8-96b6-c5d21073406b.png)

### Expected Behaviour:

Only relevant urls should be there in the `entrypoint`.
### Steps to reproduce:

Run hydrus using a parser generated doc
### Do you want to work on this issue?

NO

**Comment by vaibhavchellani** [comment]
Fixed #241

**Comment by vaibhavchellani** [comment]
Fixed #241
