### ISSUE TITLE
test_crud.py uses a different method to import the doc

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#240]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

`hydrus/tests/test_crud.py` uses a different method to import the doc.
```python
from hydrus.data import doc_parse
from hydrus.samples.doc_writer_sample import api_doc as doc
```
```python 
    def setUpClass(self):
        """Database setup before the CRUD tests."""
        self.doc = doc
        test_classes = doc_parse.get_classes(self.doc.generate())
```
Fix this and make the import format consistent across all the tests.
### Expected Behaviour:

All tests should use the same format.

### Steps to reproduce:

Compare `test_crud.py` with `test_app.py` and `test_auth.py`.
### Do you want to work on this issue?

NO

**Comment by vaibhavchellani** [comment]
fixed #243
