### ISSUE TITLE
Creation of generalised tests

### ISSUE THREAD

**Issue by vaibhavchellani** [HTTP-APIs/hydrus#246]
### I'm submitting a 
- [ ] bug report.
- [X] feature request.

### Current Behaviour:

Since the tests were written for testing the doc_maker and doc_writer the tests are written specifically for that and hence are hard coded at various places . Its not possible to test various api docs using these tests , generalising helps us test any api doc generated .
### Expected Behaviour:

We will be able to test every api doc created with the current tests 

### Do you want to work on this issue?

YES

**Comment by xadahiya** [comment]
I think you can use `doc_parser.py` to achieve this, more specifically functions like `doc_parse.get_classes()`, `doc_parse.get_properties()` and similar functions can be used to construct objects based on the classes present in the APIDoc.

**Comment by vaibhavchellani** [comment]
fixed #251
