### ISSUE TITLE
Import error from gevent

### ISSUE THREAD

**Issue by vddesai1998** [HTTP-APIs/hydrus#254]
In last few versions of 'gevent' `gevent.wsgi` was deprecated and in the new version it is completely removed. As we are using it in hydurs (cli.py - line 11), we get ImportError on running hydurs.

It should be replaced with `gevent.pywsgi`

**Comment by vaibhavchellani** [comment]
yeah i faced this too , forgot to create an issue , thanks @vddesai1998

**Comment by xadahiya** [comment]
Thanks Vishal, please create a PR to fix this issue.
