### ISSUE TITLE
Failing tests in master branch

### ISSUE THREAD

**Issue by PrajwalM2212** [HTTP-APIs/hydrus#271]
### I'm submitting a 
- [ ] bug report.

### Current Behaviour:
2 tests are failing 

### Expected Behaviour:
All tests should pass

### Steps to reproduce:
Run the tests 

### Do you want to work on this issue?
Yes , but i would need help

**Comment by PrajwalM2212** [comment]
<img width="1680" alt="screen shot 2018-09-14 at 6 11 12 pm" src="https://user-images.githubusercontent.com/30733262/45551061-5d777280-b84a-11e8-9020-719dec18c259.png">
<img width="1680" alt="screen shot 2018-09-14 at 6 11 05 pm" src="https://user-images.githubusercontent.com/30733262/45551066-62d4bd00-b84a-11e8-92be-fb23ac4a843c.png">

**Comment by PrajwalM2212** [comment]
Two tests are failing in the master branch. This may be a serious issue.

**Comment by Mec-iS** [comment]
It seems that the YAML file for the example is missing.
Have you tried to generate the YAML file by running the OpenAPI parser?

@vaibhavchellani @sandeepsajan0 ^

**Comment by Mec-iS** [comment]
the errors are pretty self-explanatory. Are you investigating?

**Comment by PrajwalM2212** [comment]
<img width="1680" alt="screen shot 2018-09-17 at 9 57 00 pm" src="https://user-images.githubusercontent.com/30733262/45636215-bf431100-bac4-11e8-8037-a3a9454276c2.png">
<img width="1680" alt="screen shot 2018-09-17 at 9 56 55 pm" src="https://user-images.githubusercontent.com/30733262/45636217-c0743e00-bac4-11e8-99af-64a384edda91.png">

I tried to generate the YAML file by running the OpenAPI parser, but wound up with these errors

**Comment by PrajwalM2212** [comment]
![image](https://user-images.githubusercontent.com/30733262/45636811-5fe60080-bac6-11e8-8112-7c1d18107054.png)

The initial error for test failure says that there is no YAML file , but it has existed all along . I wonder why it is not able to open it
