### ISSUE TITLE
Make openapi_parser.py PEP8 complaint.

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#280]
openapi_parser is not PEP8 compliant. See this 
![screenshot_2018-11-11 pep8 online check - results 2](https://user-images.githubusercontent.com/9114274/48315514-43b19c00-e5fd-11e8-8c7f-9f6e110eac31.png)

**Comment by xadahiya** [comment]
Also, users should be able to run tests from any directory ( not just the tests directory). So no relative file imports should be used.

**Comment by usmanmuhd** [comment]
Can I take this up?
