### ISSUE TITLE
Adapt and modify tests in test_app.py

### ISSUE THREAD

**Issue by vddesai1871** [HTTP-APIs/hydrus#296]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Currently, tests in test_app.py are not testing(asserting) the behaviour of the app correctly. For most of the tests, it is not even executing the code which is supposed to test the functionality.
1) In test_Collection_GET and few other tests, we are treating the endpoint as collection name instead of extracting collection name from the endpoint.
2) In test_put_at_id: we are using integers instead of using `uuid`s to test the app
3) In test_put_at_ids: we are using wrong `url` to make the request
4) regular expression to fetch ID is outdated, we should use regex for uuid.
5) Some methods like `DELETE` for collection class is not defined in the sample document we are using, so it should be added.
6) Same goes for class with endpoints, they should be added to the documentation.
### Expected Behaviour:

Every test should be executed.
Tests should use a general documentation we are using right now but with all the functionality supported by `hydrus`, so it can be tested properly. we can update the ApiDoc whenever we add a new functionality to `hydrus`.
### Steps to reproduce:

Try to make a test fail by a false assertion in test_app.py starting from test_Collection_GET, it will still pass because the assertion statements are not being executed for most of the tests.
### Do you want to work on this issue?

YES

**Comment by xadahiya** [comment]
fixed in #299
