### ISSUE TITLE
A Starting Design for the Endpoints

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#3]
This is a more general overlook about the API's endpoints. The implementation described here is the application of the use-case no.2 described [here](https://github.com/HTTP-APIs/hydrus/issues/2#issue-206778515) in issue #2 .

For the use-case no.2, the demo API we are going to develop is about Commercial Off The Shelves (COTS) spare parts for pico- and nano-satellites. Has been a recent trend in commercial space industry to develop super-light and super-compact satellites for the sake of research, prototyping, Earth observation and product testing. 

The kind of parts we are talking about are basically microcontrollers and processors that allows the spacecraft to operate. Each of these "boards" is meant to provide a function; there are 8-9 different functions (subsystems) to be carried on for the spacecraft to accomplish its mission. Some of them are critical, some other are supporting functions but likely almost every spacecraft needs almost all of them to work properly. This is a comprehensive list as they are written in the "subsystems" vocabulary:
* propulsion
* primary power
* backup power
* thermal active
* thermal passive
* structure
* command and data handling
* communication
* attitude and navigation (AODCS) active or passive

This API will serve objects related to this kind of hardware. The simple starting endpoints can be:
* `/api/cots/`: from which the single hardware parts are store and retrieved. In particular:
    * `GET /api/cots/<id>` to fetch a particular object,
    * `PUT /api/cots/<id>` to store a new object with some characteristics
    * `PATCH /api/cots/<id>`: only for some properties
    * `DELETE /api/cots/<id>`

Mandatory fields for every category of subsystem are specified in the vocabulary itself.
An example of COTS spare part is represented by this JSON, this is a backup power subsystem:
```
{
    "id": 1, 
    "object": {
        "category": "backup power", 
        "maxWorkingTemp": 61, 
        "volume": 126, 
        "minWorkingTemp": -21, 
        "mass": 252, 
        "power": 638, 
        "cost": 10208
    }, 
    "name": "2KV backup power",
    "year": "2015",
    "manufacturer": "Invented Corp."
}
```

This JSON is ported into a JSON-LD using this two vocabularies: one for the [spacecraft](http://ontology.projectchronos.eu/documentation/spacecraft), one for [different subsystems](http://ontology.projectchronos.eu/documentation/subsystems) :
```
{ 
    "@context": {
        "spacecraft"  : "http://ontology.projectchronos.eu/spacecraft/",
        "subsystems"  : "http://ontology.projectchronos.eu/subsystems/"
    },
    "@id": "/api/cots/1",
    "@type": "spacecraft:Subsystem_Spacecraft",
    "subsystems:subSystemType": "subsystems:Spacecraft_BackupPower",
    "subsystems:function": "Backup and restore energy if Power no. 1 goes down",
    "subsystems:isStandard": "Cubesat",
    "subsystems:maxWorkingTemp": 61, 
    "subsystems:volume": 126, 
    "subsystems:minWorkingTemp": -21, 
    "subsystems:mass": 252, 
    "subsystems:power": 638, 
    "subsystems:cost": 10208,
    "subsystems:manufacturer": "Invented Corp."
    }, 
    "skos:name": "2KV backup power",
    "subsystems:year": "2015"
}
```

* `/api/spacecraft/<id>`: an assembled group of COTS that can be used to make up an actual satellite. Each COTS object is categorized into a group that represents its function. For this endpoint:
    * `GET /api/spacecraft/<id>`: retrieve a blueprint
    * `PUT /api/spacecraft/<id>`: create a new blueprint 
    * `PATCH /api/spacecraft/<id>`: emend some component of the blueprint
    * `DELETE /api/spacecraft/<id>`: remove ablueprint
As for the subsytem objects above a JSON and a JSON-LD desctiption will be provided.

These are the endpoints that need to be served by the server with the proper description provided using the HYDRA framework.

**Comment by pchampin** [comment]
\<nitpicking>
creating a new object whould be either
* ``POST /api/cots/``
or 
* ``PUT /api/cots/<id>`` (with a fresh id)
\</nitpicking>

**Comment by Mec-iS** [comment]
@pchampin I am opinionated in using `PUT` (:
In term of fluency `POST` always sounds very generic to me compared to `PATCH`. 
But for sure we can implement both.

**Comment by pchampin** [comment]
I agree about ``POST`` being very (too?) generic, and I too like ``PUT`` for creating new resources (and ``PATCH`` for modifying them without sending the whole representation).

But my point was: if you are using ``PUT`` to create a resource, then you must address the request to the IRI of the to-be-created resource (hence the ``<id>`` in the target IRI). If you don't/can't know in advance that IRI, this can't be a PUT, and so I know no better solution than ``POST``...

**Comment by Mec-iS** [comment]
Sorry, I forgot the id as a URL parameters for `PUT`s.

Yeah, that's why we should support both. If the user for his/her own sake wants to give a particular id (that is the right range for the API) he/she can do it; otherwise they can use `POST` and get an auto-assigned id.

**Comment by ddxgz** [comment]
Should it go strictly follow the REST constrains including HATEOAS, or apply flexibly?

For creating a new object, I prefer using POST (user specified ID could be contained in the post data body), since when doing a PUT to /objects/<id>, the target object should be already existed.

**Comment by fractos** [comment]
Just as an aside, when we were creating the Hydra API for the DLCS project (https://dlcs.info) we used the RESTful guidelines in this set of articles, which helped answer a few questions that seemed to be ambiguous about how to organise the URLs: http://restful-api-design.readthedocs.io/en/latest/intro.html

The API we have has a URL scheme like the following:

https://api.dlcs.io/customers/{customer-id}/spaces/{space-id}/images/{image-id}

The inclusion of the customers/spaces/images parts of the URL allow easily defined endpoints to POST t (and receive a Location header back), while the {xxx-id} parts are the endpoints for PUT/PATCH/DELETE. GET allowed on both, yielding a paged collection or an entity.

**Comment by pchampin** [comment]
>
> Should it go strictly follow the REST constrains including HATEOAS, or
> apply flexibly?
>
PUT to create resources does not contradict REST nor HATEOAS.

> For creating a new object, I prefer using POST (user specified ID could be
> contained in the post data body),
>
Specifying the ID in the POST body is indeed possible, but not standard, so
it increases the coupling between the client and the server (note that the
[Slug header from the Atom protocol](
https://tools.ietf.org/html/rfc5023#section-9.7) can still be used to
*suggest* and ID, but not *specifiy* it).

> since when doing a PUT to /objects/, the target object should be already
> existed.
>
Nothing in the definition of PUT imposes that.

**Comment by chrizandr** [comment]
As applications for GSoC have started, here is a document I wrote regarding possible solutions and other specifications for the design. 
Your feedback and views are highly appreciated. The document allows comments so please feel free to write your suggestions

https://docs.google.com/a/iiits.in/document/d/1YjGPwoIQh9af3OdppSBmCHaEAez8kMRy-9F9WXttQiw/edit?usp=sharing

I will write the final proposal once I get feedback from mentors on this document.

Looking forward to working with you,

Regards,
