### ISSUE TITLE
Generic Refactoring

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#303]
### Current Behaviour:
Some code is not readable and some optimization should be applied. For example:
* URL formatting should be using: `str.format()`: `'{}/{}/{}'.format(..., ..., ...)` or better `f'{domain}/{path}/{id}'`
* issue #301
* please @chrizandr @xadahiya add to the list
* Adding doc strings wherever missing

### Expected Behaviour:
Code should be refactored

**Comment by pradeepgangwar** [comment]
@Mec-iS Allow me to work on this.

**Comment by Mec-iS** [comment]
You don't need to ask for permission. Please get familiar with Github Workflow (forking, branching, pull requests, etc).

**Comment by vddesai1871** [comment]
> better f'{domain}/{path}/{id}'

@Mec-iS Python 3.5 does not support f-string.
We can use any clever hacks available out there but it makes sense to use plain old string.format

**Comment by xadahiya** [comment]
I don't think there's any nice way to use fstrings in python 3.5 right now. If we want to use fstrings then we might have to ditch python 3.5, not sure we should do that. 
If think it would be better if we stick we old string formatting, for now at least.

**Comment by de-sh** [comment]
I will work with str.format() in case you decide to remain with python3.5

**Comment by de-sh** [comment]
All tests are passing on this one :100: 🎉

**Comment by xadahiya** [comment]
Fixed in #316

**Comment by vddesai1871** [comment]
@xadahiya can you reopen it and add "Adding doc strings wherever missing" in the list. And doc strings right now doesn't describe possible exception which a function can raise, so it would be nice to add those also.

**Comment by de-sh** [comment]
Have we considered moving to [Pipenv](https://pipenv.readthedocs.io/en/latest/)? I personally recommend using it, with the Pipfile, one could easily better segragate dependencies and stuff.

**Comment by newbazz** [comment]
i think different issue should be opened for refactoring different files, as it will allow easy readability and easier management.

**Comment by HarsheetKakar** [comment]
Can I start working on this issue?
