### ISSUE TITLE
Write tests to check PEP8 compliance

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#312]
### I'm submitting a 
- [ x ] feature request.

Write unit test to check PEP8 compliance

**Comment by Mec-iS** [comment]
we need to add pylint to the CI pipeline, then

**Comment by de-sh** [comment]
I would like to take this up. Any suggestions you'd like me to follow?

**Comment by xadahiya** [comment]
Fixed in #319
