### ISSUE TITLE
Move examples file into `examples`

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#322]
`petstore_openapi.yaml`, like any other examples-related data, should be in the `examples` directory.

**Comment by Mec-iS** [comment]
Same for `doc.jsonld`

**Comment by newbazz** [comment]
I would like to work on this issue.

**Comment by knakul853** [comment]
actually i'have made pr on this issue :p

**Comment by Mec-iS** [comment]
@newbazz you don't need ask for permission. Please follow Github Workflow

**Comment by newbazz** [comment]
I think this issue should be closed as it already has the PR approved and merged.
