### ISSUE TITLE
Fix vulnerability for current version of pyyaml

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#323]
Report about details of this vulnerability and how to fix it:
https://github.com/HTTP-APIs/hydrus/network/alerts

Then open a PR with the fix.

**Comment by Mec-iS** [comment]
@newbazz the link is accessible only to repository collaborators I suppose.
Here a screenshot:

![pyyaml-vulnerability](https://user-images.githubusercontent.com/3146196/50726264-93df4300-1102-11e9-914c-5ea59de2ec63.png)

**Comment by chrizandr** [comment]
Fixed in #331
