### ISSUE TITLE
Make OpenAPI parser into its own repository

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#330]
The OpenAPI -> Hydra parser should be segregated into its own repository and downloaded by hydrus via `requirements.txt`. It may be also published in PyPi eventually.

**Comment by chrizandr** [comment]
There is also a new sub-module feature on GitHub, where we link separate repositories into existing ones as sub-modules. Maybe we can explore that as well?

**Comment by ShravanDoda** [comment]
Is it necessary to put into  `requirements.txt`? After creating a separate Repo for OpenAPI, I added the following code to my setup.py file -- 
`parserUrl = "https://github.com/ShravanDoda/parser"`
`os.mkdir(os.path.join(os.getcwd(), 'hydrus/parser'))`
`os.system("git clone {} hydrus/parser".format(parserUrl))`

**Comment by Mec-iS** [comment]
@ShravanDoda you can use `git+git://` directly in the requirements: https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source

**Comment by newbazz** [comment]
can i work on this issue? As i have already done one beginners issue?

**Comment by ShravanDoda** [comment]
I created a python project for parser with setup.py and sdist. I'm able to install it directly from my terminal via git+git/git+https but with requirements.txt it throws an error.
`Could not find a version that satisfies the requirement parser (from hydrus==0.0.1) (from versions: )`

**Comment by ShravanDoda** [comment]
I created a python package for parse with setup.py and sdist. I'm able to download it to hydrus with requirements.txt by specifying the dependency_links in setup.py. But in order to make it work properly I'll have to change all the references of parser in the import statement. Is this the right way?

**Comment by ShravanDoda** [comment]
> I created a python package for parse with setup.py and sdist. I'm able to download it to hydrus with requirements.txt by specifying the dependency_links in setup.py. But in order to make it work properly I'll have to change all the references of parser in the import statement. Is this the right way?

Here's the link to parser repo: https://github.com/ShravanDoda/parser

**Comment by de-sh** [comment]
Sorry I couldn't update you guys before the PR, issue is solved, but had to make a PyPi package. Nice new lesson for me! :smile:

**Comment by Mec-iS** [comment]
Work on this has to be moved here -> https://github.com/HTTP-APIs/hydra-openapi-parser

**Comment by Mec-iS** [comment]
yeah take the parser code out of hydrus but keep the history for the that part of the codebase

**Comment by Mec-iS** [comment]
https://github.com/HTTP-APIs/hydra-python-core created for `hydraspecs`

**Comment by xadahiya** [comment]
Done https://github.com/HTTP-APIs/hydra-openapi-parser
