### ISSUE TITLE
Move hydrus to using Pipenv

### ISSUE THREAD

**Issue by de-sh** [HTTP-APIs/hydrus#334]
### Why?
This helps with managing the dependent python version for hydrus to also be backward compatible. 
- Also the Pipfile.lock exercises caution with the use of SHA hashes to maintain integrity of dependencies. 
- Pipenv also provides a shell with auto-loading features to load env. variables, which might come in handy in the future.

### How?
- loading pipenv to install from requirements.txt, then deleting requirements.txt once Pipfiles generated.
- Locking Pipfile once version of Python set to 3.5.2.

### Do you want to work on this issue?
yes

**Comment by chrizandr** [comment]
Putting this here for reference.
https://github.com/HTTP-APIs/hydrus/pull/335#issuecomment-451735167

**Comment by Mec-iS** [comment]
Postponed
