### ISSUE TITLE
Using `with` keyword to handle file Input/output.

### ISSUE THREAD

**Issue by ujjwalrox** [HTTP-APIs/hydrus#343]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Currently, file handling is done without `with` keyword, which in fact is dangerous because if an exception occurs before the call to `close()` then `close()` will not be called and the memory issues can occur, or the file can be corrupted.

Ref: [Python Official docs](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files)

### Expected Behaviour:

The file will always be closed even if some exception has occurred. 

### Do you want to work on this issue?

Yes

**Comment by Mec-iS** [comment]
merged
