### ISSUE TITLE
refactoring in doc_maker

### ISSUE THREAD

**Issue by aribalam** [HTTP-APIs/hydrus#348]
I have a few suggestions - 
1. Currently the `doc_maker` has a number of `doc_keys` defined inside functions which creates classes, properties, operations and statuses to check for those keys. Since those are all hard-coded and are subject to changes, what if we put all those keys in one place as global declarations?
We could then map those keys to their respective `body_type` and use it accordingly.
2. The two functions `class_in_endpoint` and `collection_in_endpoint` has class dictionary as its param which is used only for its title inside the function. We could only pass its title as a param instead of the whole dictionary

**Comment by xadahiya** [comment]
@aribalam please move this to https://github.com/HTTP-APIs/hydra-python-core.

Closing this
