### ISSUE TITLE
Implement migrations with Alembic

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#349]
### I'm submitting a 
- [x] feature request.

### Current Behaviour:
The server should provide a standard migration tools to handle any change in schemas. The most popular migration tool for SQLAlchemy is [Alembic](https://alembic.sqlalchemy.org/en/latest/)

### Expected Behaviour:
All changes in the database schema should be tracked and reproducible

**Comment by aribalam** [comment]
@Mec-iS I am not able to understand the goal of this feature. What are we going to achieve with this. Is it related with including property attributes in the database (#226)?
Currently only the relationships between classes and properties (the triples) are being stored in a database. With property constraints and other sorts of validation to be performed by `HydraDoc` in `resources.py` as was decided in #226, there would hardly be any change in schemas.

**Comment by chrizandr** [comment]
@aribalam There might be changes we make to the DB in that would change the schema. It is a good practice to have migrations in place to make the transition easier, without having to clean the entire database.

**Comment by Mec-iS** [comment]
Implementing Alembic is a step-stone for allowing on-the-fly ApiDoc updates (e.g. change the classes definition without hard-coding the client, or "dynamic paths"). A note:

> For now we want the mechanism to run smoothly, leaving all these concerns for the second phase of the implementation. So probably at the moment we want to apply the migrations for the new models and restart the server. In a second phase we will carefully look into the data consistency issue (the first solution that comes to my mind is to have a temporary cache for all the operations that happen at server restart or to keep an log of events so to re-establish consistency after the new models are up)

**Comment by Guttz** [comment]
Okay so while implementing this I realized that **there are two situations into the same issue**, which also had me confused for a while now:

**1 -** Alembic migrations with the intent of **on-the-fly ApiDoc**(Modification on the structure of the API)
**2 -** Migrations with the intent of occasionally giving the users a way to maintain their data **in the case we change how we store the relationships** inside hydrus

##### On-the-fly ApiDoc updates
And the thing is, with the way hydrus DB structure was implemented, On-the-fly ApiDoc updates are already supported as you can see in the demo gif below. You can edit the ApiDoc, modify properties, delete classes and by the fact that the database is used only to map the relations, hydrus will be able to persist the data. 
![Dynamic Endpoint Gif](https://i.imgur.com/tatfapU.gif)
(Click on the gif to expand) 

##### DB Schema modification

As described by @chrizandr:
> @aribalam There might be changes we make to the DB in the future that would change the schema...

In this scenario, we would have, for example, some users that are already using hydrus/some servers that are live with data on their DB. And then if we make a modification in the DB structure, and these users want to upgrade their hydrus while maintaining the Data they already have in their DB, **we** have to write and provide a migration script with the hydrus upgrade. Is important to note that we cannot tell how the DB Schema will be modified, so we cannot actually create a script for migrations. What we can do is setup Alembic and some instructions on how to write the script on eventual migrations we might have. 

@Mec-iS 
@chrizandr tell me if you agree with the second part.

**Comment by Mec-iS** [comment]
Exactly. We need to support Alembic so users can change their schemas as they need (hopefully via a CLI command).

**Comment by vddesai1871** [comment]
Merged in #389
