### ISSUE TITLE
Check for incomplete docstrings and complete them

### ISSUE THREAD

**Issue by vddesai1871** [HTTP-APIs/hydrus#356]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

In many files docstrings are incomplete, some does not describe parameters and return values. 
### Expected Behaviour:

Every docstring must describe all parameters, return value and raised exceptions of the function being documented.
### Do you want to work on this issue?

No

**Comment by thrishik7** [comment]
I would love to work on this issue. I have gone through the docs, if Im stuck in somewhere please guide me.

**Comment by Mec-iS** [comment]
please join Slack and ask for help there

**Comment by thrishik7** [comment]
@Mec-iS  sure, thank you :)

**Comment by som23ya** [comment]
can i work on this?

**Comment by xadahiya** [comment]
You don't need to ask for permission. Please feel free to work on whatever issue you like or create your own and submit a PR

**Comment by khabdrick** [comment]
Hello @xadahiya  is this issue still open?

**Comment by sajen-k** [comment]
is this open ?
