### ISSUE TITLE
Remove doc.py from `hydrus serve` command

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#360]
### I'm submitting a 
- [ X] bug report.
- [ ] feature request.

### Current Behaviour:
When `hydrus serve` is run after installation, this error occurs:
```
No Hydra ApiDoc file to load has been found at site-packages/hydrus-0.1-py3.6.egg/examples/drones/doc.py
```

### Expected Behaviour:
server should run. If there is no ApiDocumentation to load, an error message should be print in stdout telling what to do to generate an ApiDoc or where to find an example to use.

**Comment by pydevsg** [comment]
I would like to work on this issue, @Mec-iS .

**Comment by Mec-iS** [comment]
no need to ask, open a Pull Request as per [Github Flow](https://guides.github.com/introduction/flow/) when you have something done.

**Comment by pydevsg** [comment]
Okay, @Mec-iS .

**Comment by de-sh** [comment]
@Mec-iS in which environment does this error occur? 
I get the following in mine
```
Setting up the database
Creating models
Creating the API Documentation
No hydradoc specified, using sample hydradoc as default.
Adding Classes and Properties
Adding authorized users
Creating the application
Starting the application
Server running at:
http://localhost:8080/serverapi
```

**Comment by Mec-iS** [comment]
This was from Windows user in the chat

**Comment by knakul853** [comment]
@Mec-iS  
```what to do to generate an ApiDoc ``` for this can we provide this on stdout
https://www.hydraecosystem.org/01-Usage.html#newdoc 
telling how to create ApiDoc object?

**Comment by knakul853** [comment]
@Mec-iS  ok

**Comment by Guttz** [comment]
This was already solved by @de-sh on https://github.com/HTTP-APIs/hydrus/commit/1b9aa2ef733cbc575249a924cd48590e6a8fb5df on the dev branch.

Current state:
![Group (4)](https://user-images.githubusercontent.com/11739405/57533013-07a58c80-733d-11e9-8f8a-fc2a28ccdc1d.png)

I guess this can be closed.
