### ISSUE TITLE
Wrong imports in cli.py

### ISSUE THREAD

**Issue by invinciblycool** [HTTP-APIs/hydrus#363]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
 - ModuleNotFoundError is caused due to a wrong import [here](https://github.com/HTTP-APIs/hydrus/blob/a3b0e8083c9717cafd71aa62cddb9fc7c0f9bce5/cli.py#L12)
 - Also, due to a wrong import [here](https://github.com/HTTP-APIs/hydrus/blob/a3b0e8083c9717cafd71aa62cddb9fc7c0f9bce5/cli.py#L4), the `serve_forever()` method is called two times which leads to no logs being logged.

### Steps to reproduce:
Run `python cli.py serve` or `hydrus serve` after installing hydrus.

### Possible fixes

 - Changing `hydrus` to `hydra`.
 - Change `hydrus.app` to `hydrus.app_factory`

**Comment by de-sh** [comment]
Hey @invinciblycool I am working on this, can you help me add more such typos to be corrected?

**Comment by Mec-iS** [comment]
Use the same PR please
