### ISSUE TITLE
Switch all provisioning scripts to use PyPI

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#367]
As hydrus is now on PyPi, all the scripts involved in the installation should use the official release on PyPi (instead of the Github repository).

**Comment by codehawkdevs** [comment]
![Screenshot from 2019-03-20 17-46-33](https://user-images.githubusercontent.com/42430373/54683634-230fca80-4b38-11e9-997b-2889f5a7cae4.png)
When I tried to install hydrus using `pip3 install --user hydrus`, the requirement.txt file was missing. Should I make changes directly to **setup.py** file?

**Comment by Mec-iS** [comment]
You can fork the repo and open a PR from your fork

**Comment by de-sh** [comment]
@Mec-iS I think we will have to make a PyPI package for both hydra_python_core and hydra_openapi_parser.

**Comment by invinciblycool** [comment]
@codehawkdevs Try adding a `MANIFEST.in` file with `requirements.txt` in it and submit a PR. `setup.py` might not need any change.

**Comment by Mec-iS** [comment]
PyPi packages will be created when the repositories move to alpha stage. Until then we use git.
