### ISSUE TITLE
Considering HTTP/2 support, porting to Quart

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#372]
### I'm submitting a 
- feature request.

### Current Behaviour:
Flask does not have any plan for supporting HTTP/2 (current installations use reverse proxying). Quart is a web-server based on HyperCorn that has the same API as Flask but support natively HTTP/2 because it is natively asynchronous (ASGI instead of uWSGI).

### Expected Behaviour:
hydrus will need to support HTTP/2. This may be needed for #300 also

**Comment by sameshl** [comment]
@Mec-iS I would like to take this up. Looking at the Quart documentation https://pgjones.gitlab.io/quart/how_to_guides/flask_migration.html#flask-migration, it seems pretty straightforward.

/cc @xadahiya

**Comment by Mec-iS** [comment]
you are free to take a look and investigate. Please write a short report below about assessing the work needed and critical points and caveats. 

This is a old issue, at this moment I would suggest to take a look to [Starlette](https://www.starlette.io/) (e.g. FastAPI) that seems a fresher implementation.

**Comment by sameshl** [comment]
> you are free to take a look and investigate. Please write a short report below about assessing the work needed and critical points and caveats.

Yes, I will first do a analysis on what important changes need to be done in `hydrus`

> This is a old issue, at this moment I would suggest to take a look to [Starlette](https://www.starlette.io/) (e.g. FastAPI) that seems a fresher implementation.

I will go through other async frameworks as well and see which might be the best

**Comment by Mec-iS** [comment]
moved to #577 and close.
