### ISSUE TITLE
Find a type checker and run it with Travis

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#379]
### I'm submitting a 
- feature request.

### Current Behaviour:
Type annotations with `mypy` allow the code to tell developers which type of inputs/outputs are expected but there is no tool that checks that the annotations are respected by the functions

### Expected Behaviour:
Some command-line tool should run with CI to check if types annotations are correct. See [pyre](https://pyre-check.org/docs/guided-tour.html)

**Comment by Mec-iS** [comment]
another option: https://github.com/Microsoft/pyright

**Comment by sjathin** [comment]
Hello, I would like to work on this issue.  Can I work on this?

**Comment by sameshl** [comment]
@sjathin Yes, sure. Go ahead!

**Comment by sjathin** [comment]
Thank You @sameshl 

I am facing the following issue when i run **pip3 install -r requirements.txt** :

For the requirement  **git+https://github.com/HTTP-APIs/hydra-python-core@master#egg=hydra_python_core**

 Cloning https://github.com/HTTP-APIs/hydra-python-core (to revision master) to /private/var/folders/09/jdl0lzhd2k55lnhbkwyshlvh0000gn/T/pip-install-idjjp03s/hydra-python-core
  Running command git clone -q https://github.com/HTTP-APIs/hydra-python-core /private/var/folders/09/jdl0lzhd2k55lnhbkwyshlvh0000gn/T/pip-install-idjjp03s/hydra-python-core
ERROR: Command errored out with exit status 1:
 Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/09/jdl0lzhd2k55lnhbkwyshlvh0000gn/T/pip-install-idjjp03s/hydra-python-core/setup.py", line 8, in <module>
        dependencies = [str(package.requirement) for package in install_requires]
      File "/private/var/folders/09/jdl0lzhd2k55lnhbkwyshlvh0000gn/T/pip-install-idjjp03s/hydra-python-core/setup.py", line 8, in <listcomp>
        dependencies = [str(package.requirement) for package in install_requires]
    AttributeError: 'InstallRequirement' object has no attribute 'requirement'


Can you please let me know if there is anything i am missing ?

My environment:
MacOS
pip 20.0.2
Python 3.7.7

**Comment by priyanshunayan** [comment]
Hi @sjathin! You should no longer face this issue as this was fixed in #500. Can you try running the latest revision of hydrus again?

**Comment by sjathin** [comment]
Hi @priyanshunayan, I do have the latest revision, I am facing this issue.

**Comment by priyanshunayan** [comment]
From your logs I can see that you are not inside the virtual environment. Indeed, the documentation is missing this step. I will make sure this gets added in the docs. In meantime please follow following steps before pip install:
* `python3 -m venv venv`
* `source venv/bin/activate`
* `pip3 install -r requirements.txt `

/cc @sjathin

**Comment by farazkhanfk7** [comment]
@priyanshunayan  @Mec-iS Can I work on this ? I am just starting with hydrus and if you'll allow me should I add a PR to add instructions for setting up a virtual environment before running  `pip3 install -r requirements.txt` and `python3 setup.py install` ?

**Comment by de-sh** [comment]
Hello folks, I have an interesting opinion about this issue, how about we add a static analyzer such as [DeepSource](https://deepsource.io) to the CI?

**Comment by saif007sm** [comment]
i am beginner in the issues can you please suggest me how to get started

**Comment by saif007sm** [comment]
i am beginner in the issues can you please suggest me how to get started

**Comment by DARKPROGRAMMER16** [comment]
I am facing up some issue while seeing up hydros. Can anyone help me out with this.

while running the command  - **pip3 install -r requirements.txt**

the error thrown is : 

ERROR: Command errored out with exit status 1:
     command: /Users/apple/Desktop/hyd/env1/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5l/k69p9lld7xv687yc1tmt18640000gn/T/pip-install-2lu6ue9d/psycopg2/setup.py'"'"'; __file__='"'"'/private/var/folders/5l/k69p9lld7xv687yc1tmt18640000gn/T/pip-install-2lu6ue9d/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5l/k69p9lld7xv687yc1tmt18640000gn/T/pip-pip-egg-info-p9gqy69k
         cwd: /private/var/folders/5l/k69p9lld7xv687yc1tmt18640000gn/T/pip-install-2lu6ue9d/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /private/var/folders/5l/k69p9lld7xv687yc1tmt18640000gn/T/pip-pip-egg-info-p9gqy69k/psycopg2.egg-info
    writing /private/var/folders/5l/k69p9lld7xv687yc1tmt18640000gn/T/pip-pip-egg-info-p9gqy69k/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/5l/k69p9lld7xv687yc1tmt18640000gn/T/pip-pip-egg-info-p9gqy69k/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/5l/k69p9lld7xv687yc1tmt18640000gn/T/pip-pip-egg-info-p9gqy69k/psycopg2.egg-info/top_level.txt
    writing manifest file '/private/var/folders/5l/k69p9lld7xv687yc1tmt18640000gn/T/pip-pip-egg-info-p9gqy69k/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.



My system - 
_MacBook Air 2019
Mac OS catalina
python version - 3.9.1_

**Comment by king-11** [comment]
@DARKPROGRAMMER16 you are using the dev branch or the master? coz the issue in dev branch is resolved

**Comment by DARKPROGRAMMER16** [comment]
> @DARKPROGRAMMER16 you are using the dev branch or the master? coz the issue in dev branch is resolved

dev branch

**Comment by DARKPROGRAMMER16** [comment]
@king-11 

I am in dev branch

**Comment by king-11** [comment]
@DARKPROGRAMMER16 is your error code in any way similar to this https://github.com/psycopg/psycopg2/issues/854#issuecomment-611687343

**Comment by Mec-iS** [comment]
this content is not related to this issue. For any question, first use Slack and search for past issues or Google. If there is no other reference, open a new issue. Please follow Code Contribution rules.
