### ISSUE TITLE
Upgrade Flask version to latest

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#382]
### I'm submitting a 
- [ ] bug report.

### Current Behaviour:
We are running a dated version of Flask

### Expected Behaviour:
We shall use the latest stable

Also check other requirements for stale versions.

**Comment by kurianbenoy** [comment]
Hey @Mec-iS, I am a bit confused by your statement dated version of Flask. On checking [change logs](http://flask.pocoo.org/docs/1.0/changelog/) the current version of Flask in 1.0.2 is already the latest stable version.

**Comment by Mec-iS** [comment]
you are right, I misread from an old local branch
