### ISSUE TITLE
Paginated collections using IriTemplating

### ISSUE THREAD

**Issue by vddesai1871** [HTTP-APIs/hydrus#397]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Expected Behaviour:

hydrus should provide support for client initiated pagination.
When the client initiated pagination is enabled(at server side) , hydrus(server) will add necessary mappings in the IriTemplate of the collection response and as mentioned in the spec the client will use that to pass query (pageIndex/limit/offset) values.
When disabled, hydrus won't add pagination related IriTemplate to the response, so client won't be able to use client initiated pagination. 
We will need to add searching(IriTemplate) mechanism before implementing it, so I am postponing it for now.

### Do you want to work on this issue?

YES

Edit: Edited to avoid ambiguity related to disabling/enabling pagination. Only server can enable/disable any kind of pagination.

**Comment by chrizandr** [comment]
Should we allow the client to modify pagination? We assume that there are multiple clients contacting the server at any given time, would one client then paginate the results for all? How do we separate that for each client? 
I think pagination is a feature that should be enabled and disabled at the server end.

Let's discuss this before proceeding.

**Comment by vddesai1871** [comment]
>I think pagination is a feature that should be enabled and disabled at the server end.

Yes that's true, I think we have some misunderstanding here,  by client initiated pagination we do not mean that clients will be able to enable or disable it. It can only be enabled or disabled at the server side. Once enabled, it will provide an IriTemplate related for pagination, that can be used by any client without interfering with how other clients are interacting with the server.

**Comment by chrizandr** [comment]
> Yes that's true, I think we have some misunderstanding here, by client initiated pagination we do not mean that clients will be able to enable or disable it. It can only be enabled or disabled at the server side. Once enabled, it will provide an IriTemplate related for pagination, that can be used by any client without interfering with how other clients are interacting with the server.

In that case it would be wrong to call it client initiated. The client will only send requests for the page number/offset it needs. Pagination itself is a server side feature.

**Comment by Guttz** [comment]
[Adding for documentation references]

 Hydra Spec ref for this: https://www.hydra-cg.com/spec/latest/core/#client-initiated-pagination

**Comment by Mec-iS** [comment]
This has to be done with #302
