### ISSUE TITLE
Choosing a framework for backend/server

### ISSUE THREAD

**Issue by chrizandr** [HTTP-APIs/hydrus#4]
To the best of my knowledge, here are some of the key factors I think you should considered while reviewing python based web frameworks:

- Framework Architectures
- Community Support
- Supported Tools
- Robustness and Scalability
- Flexibility
- Learning curve

The three frameworks that are most used out there would definitely be **Django**, **Pyramid** and **Flask**
I would like for everyones opinions on which framework would be suitable to build the demo web application.

Here is what I think:

- Both Django and Pyramid follow an MVC based architecture, this allows them to isolate their data, views and controllers natively. Both these frameworks also insist on good coding practices when it comes to arrangement of code. Flask on the other hand is a micro-framework, as such everything must be defined from scratch, this however, allows more flexibility, although from my experience the other two have good workarounds for almost everything.
- Django has by far the largest community along with lots of documentation and a number of tutorials, including their own well documented tutorials that are extremely useful in getting started. I don't know much about Pyramid's documentation, maybe someone else can comment upon it. Flask has minimal basic documentation and there are a number of tutorials for it too. Given the ease of use of Flask, much documentation isn't needed for developement.
- Django and Pyramid come with a number of built in tools to help the developement process. It also reduces developement time by a large amount by having server implementations such as security, requests and access control built in. Flask offers the basic necessities in the same areas, but additional features may need to be implemented.
- Robustness and scalability wise, both Django and Pyramid beat Flask. Flask is a micro-framework which was essentially designed for small scale applications. Although I haven't used Flask myself, this is what is mentioned on their website.
- Learning curve of all the three would be the easiest for Flask, with most people being able to start developement almost instantly. Django has a steep learning curve and I don't have much knowledge about Pyramid.

Given the fact that this project would lay the foundation stone for something bigger, I would suggest using something robust that would be both extendable and scalable. There is no saying as to what the project might branch out into in the future and as such, a strong foundation would be recommended. Keeping this in mind, I would suggest that Django be used for developement. 

This is purely my opinion and I would like for alternate views on the same.
Extremely sorry if this thread was unnecessary, but I felt that it was better to have some sort of discussion to get things started.

**Comment by pchampin** [comment]
I'm not an expert in any of those frameworks, but I know a little about Django and Flask, and a very little about Pyramid. From this little I know, I tend to agree with the points in your bullet list.

I'm not sure I agree with your conclusion, though... In my view, this is an experimental project, the primary goal of which being to demonstrate what Hydra can do that other approaches can not (or not as well). As such, we should favour flexibility and agility rather than robustness and scalability (sounding a bit like [premature optimization](http://wiki.c2.com/?PrematureOptimization)).

**Comment by Mec-iS** [comment]
@chrizandr I vote for Flask, that is the most flexible and lightweight.

**Comment by chrizandr** [comment]
Well I too had a little predisposition that Flask might be the favoured framework. The reason I suggested Django was looking from a future work point of view. 
If the project is only intended for demo/experiment purposes, then I too will be voting for Flask.

**Comment by Mec-iS** [comment]
Let's consider the option [HUG](https://github.com/timothycrosley/hug) that has, like Flask, a functional architecture. For sure there is a way to extend its API to serve JSON-LD.

**Comment by chrizandr** [comment]
@Mec-iS : It looks interesting, I'll play around with it for a while and let you know.

**Comment by ddxgz** [comment]
[Sanic](https://github.com/channelcat/sanic) could be an option, it's Flask like, but supports async request handler.

**Comment by Mec-iS** [comment]
@ddxgz Thanks. I am following the evolution of Sanic as well, and also [Japronto](https://github.com/squeaky-pl/japronto) seems great. But for the sake of this phase of the project, we need to demonstrate HYDRA features, further optimization or improvements in server architecture/performance are left to later stages. We are now in a sort of POW phase at the moment.

**Comment by xadahiya** [comment]
@Mec-iS  [Hug](https://github.com/timothycrosley/hug) is a nice option, but I think using [Django](https://www.djangoproject.com/) would be better as it is more robust and scalable. Also, we can also serve data in JSON-LD format using its REST framework.

**Comment by Mec-iS** [comment]
temporary closing. To be reopened in a later phase.
