### ISSUE TITLE
[Discussion] Research better multiple-table architecture (objetive 2021)

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#412]
Research and discuss a multiple-table database architecture where different type of resources are stored in different tables to improve scalability and efficiency.

**Comment by Guttz** [comment]
To make the discussion easier I figured it would be good to deploy an instance of the DB with an IDE.
Available at: https://sqliteonline.com/#fiddle-5d31c0c75d188js6jya4czcr @Mec-iS

![image](https://user-images.githubusercontent.com/11739405/61537518-bf29df80-aa0d-11e9-9961-b56c1f3c482f.png)

**Comment by Mec-iS** [comment]
> Available at: https://sqliteonline.com/#fiddle-5d31c0c75d188js6jya4czcr

This should go in the doc (:

**Comment by Mec-iS** [comment]
As discussed we may be moving to TTL mappings [R2RDF](https://www.w3.org/TR/r2rml/) in 2021. Further discussion to come.
