### ISSUE TITLE
Treating collections as a resource

### ISSUE THREAD

**Issue by chrizandr** [HTTP-APIs/hydrus#416]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

I've been speculating for some time now that our treatment of collections as a single resource for every class is wrong. Nowhere in the spec is it mentioned that a collection is a set of all objects for a given class. It is mentioned that a collection is "a set of somehow related resources". This does not imply that a collection would be only limited to class types
### Expected Behaviour:

 I think the direction we must move in is for users to be able to define collections on their own. Each collection itself would have an `@id` since it is a subclass of `hydra:Resource`. We then use the collection endpoint to relate classes/properties.

We use Collections directly instead of having pseudo-Collections defined by parent_id or child_id. The main problem with both the above approaches is as you mentioned, identifying the property which contains the parent/child id. This is because schema.org/identifier or hydra:Link and even https://schema.org/ItemList are general definitions that can be used for any property and need not necessarily be for only parent/child ids. The advantage of using a collection is that we define a CommentCollection object, where we link all Comment objects for a particular issue. We then give that CommentCollection object as the property for the Issue. In terms of defining it in the API documentation, it would be something like:

```
{
        "@type": "SupportedProperty",
        "property": vocab:CommentCollection,
        "readonly": "false",
        "required": "true",
        "title": "Comments",
        "writeonly": "false"
}
```
The property would map to an instance of the CommanCollection class. This will be defined in the supportedProperty field for the definition of the Issue class. Like any other object, when we define the Issue object, we will add the appropriate instance of the CommandCollection to the Issue instance. So an object would be something like:

```
{
        "@type": "Issue",
        "@id": "/api/Issues/27",
        "Issue": "....",
        "Comments": "/api/CommentCollection/32",
        ....
}
```

And then `/api/CommentCollection/32` would have:

```
{
        "@type": "CommentCollection",
        "@id": "/api/CommentCollection/32",
        "members": [
                {
                        "@id": "/api/Comment/12",
                        "@type": "Comment"
                },
                {
                        "@id": "/api/Comment/18",
                        "@type": "Comment"
                },
                {
                        "@id": "/api/Comment/22",
                        "@type": "Comment"
                }
        ]

}
```
All this is part of the bigger implementation of treating collections as a resource. We allow hydrus to implement all operations: GET, PUT, POST, DELETE on all resource endpoints as well as on all collection endpoints. We then let users decide how they design their APIs and wether creation of resources happens at the collection endpoint or the resource endpoint is defined in the API Documentation itself. Nested collection would then be added to an object as any other resource.

NOTE: We should also allow the creation of both resources(Comment) as well as collections(CommentCollection) on the collection endpoint. We let the user decide which they want to use based on the API documentation. If the doc contains a `supportedOperation` to allow creation of resource using the collection endpoint then we create resources using that. Similarly for the case of resources. Hope this is clear.

**Comment by vddesai1871** [comment]
>I think the direction we must move in is for users to be able to define collections on their own.
:+1: 

>The main problem with both the above approaches is as you mentioned, identifying the property which contains the parent/child id. This is because schema.org/identifier or hydra:Link and even https://schema.org/ItemList are general definitions that can be used for any property and need not necessarily be for only parent/child ids.

I think this problem can be solved by hydra:Link, by having a 'bidirectional' link, as Markus has used here http://www.markus-lanthaler.com/hydra/api-demo/vocab. The solution you proposed is somewhat better than such reliance on links to imply relations, but still I think we will need to have that as fallback or alternative. As we are allowing the Api Desigenr to decide whether he wants to add new resources from the item resource endpoint or collection resource endpoint, if he chooses the collection endpoint then everything will work fine and we would be able to know whether newly added object belongs to some nested collection of other item resource or not( ex. If new comment is added on api/CommentCollection/3 then we know that the issue (or anyother class) which has this collection object(with id 3) is  the parent of this new comment(basically this comment belong to that issue)) But if API designer allows addition on the resource endpoint (Comment/id) then how do we find out which issue this comment belongs to? Then only way for him to accomodate such parent child relation would be to have another link from child to the parent object. So the newly added comment will have a link to the parent issue.

**Comment by Mec-iS** [comment]
I have mentioned sometime that collections are just "alias names" for "collections of pointers" to instances. What I meant is basically that they are representation for sets of instances, this may be implemented by having the collection endpoint (the alias name) that return a sequence (i.e. list, vector) `of `HydraLinks` to proper instances. Is it specified otherwise in the specs that the member of the collection shall be resources; I suppose that we can declare the members to be of type `HydraLink`.

**Comment by Mec-iS** [comment]
@chrizandr is this solved? please close if it is

**Comment by chrizandr** [comment]
No it hasn't been implemented

**Comment by sameshl** [comment]
@chrizandr I would like to work on this feature. But, I haven't completely understood what has to been done. So could you point to the relevant code and also some links which I could use to understand about whats the current implementation and what needs to be done.

Thanks!

**Comment by sameshl** [comment]
@chrizandr Should I close this issue as most of the work involving treating collections as a resource is done? The current point of discussion is on Updating Collections which is being discussed in https://github.com/HTTP-APIs/hydrus/issues/494.

**Comment by chrizandr** [comment]
Yes, I think we can close this
