### ISSUE TITLE
General refactoring

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#424]
### Current Behaviour:
A lot of functions have many if-else branches and the procedures implemented by these branches have too much code in them. This makes readability and testability hard.

For example the branch in this [chunk of code](https://github.com/HTTP-APIs/hydrus/blob/42205ab4d4984f591310b19f3b5d6c1610e95e4d/hydrus/resources.py#L108) should be ported into a function like:
```
    if checkClassOp(class_path, "GET"):
        items_get_check_support() 
    abort(405)
```
Into a dedicated module called `itemshelpers.py` the above functions should be defined by incorporating the current code:
```
def items_get_check_support(...):
    """ Check if class_type supports GET operation
            try:
                # Try getting the Item based on ID and Class type
                response = crud.get(
                    id_,
                    class_type,
                    api_name=get_api_name(),
                    session=get_session())

                response = finalize_response(class_path, response)
                return set_response_headers(
                    jsonify(hydrafy(response, path=path)))

            except (ClassNotFound, InstanceNotFound) as e:
                error = e.get_HTTP()
                return set_response_headers(jsonify(error.generate()), status_code=error.code)
```
Each of these helpers functions should be tested separately.

### Expected Behaviour:
All functions should perform well-scoped units of work and have their own tests.
Handlers in endpoints classes should be much more concise, all the units of work for each branch should be moved into helpers functions. 

Main functions should look something like this:
```
def post(...):
    """ Docstring """
    ... some code ...
    if condition_1:
        run_helper_1(...)
    elif condition_2:
        run_helper_2(...)
    else:
        run_helper_3(...)
    ... rest of the code ...
```

**Comment by sameshl** [comment]
@Mec-iS I would love to work on this. Could you link me to some code so I could start working from there?

Thanks

**Comment by thrishik7** [comment]
@Mec-iS. Can I work on refactoring class ItemCollection

**Comment by Mec-iS** [comment]
Good job with the merged PRs. Kep this one open.

**Comment by kanavpruthi** [comment]
Is this issue still open? Can I work on it?

**Comment by sameshl** [comment]
> Is this issue still open? Can I work on it?

Yes @kanavpruthi. A lot of code could be refactored in `hydrus`, you can go ahead with this issue.

**Comment by kanavpruthi** [comment]
So do I need to have docker installed (or container based software as given in readme.md file), since I am not to familiar on using containers.

**Comment by Mec-iS** [comment]
For now we are good in terms of code clarity. Let's close this and open a new one for specific cases to refactor.
