### ISSUE TITLE
Outdated Chat Room link

### ISSUE THREAD

**Issue by vcode11** [HTTP-APIs/hydrus#426]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

The current link to chat in contributing.md refers to gitter but organization has moved to a slack channel.

### Expected Behaviour:

Link to the slack channel.

### Steps to reproduce:

Click on help in the chat in CONTRIBUTING.md

### Do you want to work on this issue?

Yes

**Comment by chrizandr** [comment]
Fixed in #427
