### ISSUE TITLE
Hydrus hardcoded for serving apiDoc

### ISSUE THREAD

**Issue by vcode11** [HTTP-APIs/hydrus#428]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Hydrus only allows serving the apiDoc at ```http://localhost:8000/api/vocab``` only which is not aligned with hydra spec.

### Expected Behaviour:
Hydrus should allow serving apiDoc as per ```https://www.hydra-cg.com/spec/latest/core/#documenting-a-web-api```

### Do you want to work on this issue?
Yes

**Comment by chrizandr** [comment]
Yes. The doc should be allowed to serve at any URI. This will then need to be added to the Link headers of the responses so that the client can access the API doc.

**Comment by Mec-iS** [comment]
This is related to https://github.com/HTTP-APIs/hydra-python-agent/issues/102

**Comment by sameshl** [comment]
@chrizandr @xadahiya I have tried to implement this feature in this [PR](https://github.com/HTTP-APIs/hydra-python-agent/pull/136) . Let me know if any thing needs to be changed.
