### ISSUE TITLE
demo returns incomplete contexts

### ISSUE THREAD

**Issue by luchsamapparat** [HTTP-APIs/hydrus#429]
### I'm submitting a 
- [X] bug report.

### Current Behaviour:
I'm exploring the hydrus demo to understand how Hydra works. From what I understand, the linked JSON-LD contexts do not provide enough information to parse a response as RDF.

Requesting the `DroneCollection` returns the following JSON-LD document:

```jsonc
// GET http://localhost:8080/serverapi/DroneCollection

{
  "@context": "/serverapi/contexts/DroneCollection.jsonld",
  "@id": "/serverapi/DroneCollection/",
  "@type": "DroneCollection",
  "members": [],
  "search": {
    "@type": "IriTemplate",
    "mapping": [
      {
        "@type": "IriTemplateMapping",
        "property": "http://auto.schema.org/speed",
        "required": false,
        "variable": "DroneState[Speed]"
      },
// ...
    ],
    "template": "/serverapi/Drone(DroneState[Speed], DroneState[Position], DroneState[Direction], DroneState[Battery], DroneState[SensorStatus], DroneState[DroneID], name, model, MaxSpeed, Sensor, pageIndex, limit, offset)",
    "variableRepresentation": "hydra:BasicRepresentation"
  },
  "totalItems": 0,
  "view": {
    "@id": "/serverapi/DroneCollection?page=1",
    "@type": "PartialCollectionView",
    "first": "/serverapi/DroneCollection?page=1",
    "last": "/serverapi/DroneCollection?page=1"
  }
}
```

However, the linked JSON-LD context does not contain mappings for all the Hydra-specific identifiers:

```jsonc
// GET http://localhost:8080/serverapi/contexts/DroneCollection.jsonld

{
  "@context": {
    "Drone": "vocab:Drone",
    "DroneCollection": "vocab:DroneCollection",
    "hydra": "http://www.w3.org/ns/hydra/core#",
    "members": "http://www.w3.org/ns/hydra/core#member",
    "vocab": "http://localhost:8080/serverapi/vocab#"
  }
}
```

Almost none of the Hydra-identifiers in the response (`search`, `IriTemplate`, `totalItems`, `first`, `last`, etc.) can be mapped to their URIs. The issue becomes obvious, when you paste the JSON-LD along with the JSON-LD context into the JSON-LD playground:

http://tinyurl.com/rrq6cc8

### Expected Behaviour:
Either the JSON-LD context maps all the identifiers to their URIs or the identifiers are prefixed with `hydra:` in the document. E.g. like this:

```jsonc
{
  "@context": "/serverapi/contexts/DroneCollection.jsonld",
  "@id": "/serverapi/DroneCollection/",
  "@type": "DroneCollection",
  "members": [],
  "hydra:search": {
    "@type": "hydra:IriTemplate",
    "hydra:mapping": [
      {
        "@type": "hydra:IriTemplateMapping",
        "hydra:property": "http://auto.schema.org/speed",
        "hydra:required": false,
        "hydra:variable": "DroneState[Speed]"
      },
// ...
    ],
    "hydra:template": "/serverapi/Drone(DroneState[Speed], DroneState[Position], DroneState[Direction], DroneState[Battery], DroneState[SensorStatus], DroneState[DroneID], name, model, MaxSpeed, Sensor, pageIndex, limit, offset)",
    "hydra:variableRepresentation": "hydra:BasicRepresentation"
  },
  "hydra:totalItems": 0,
  "hydra:view": {
    "@id": "/serverapi/DroneCollection?page=1",
    "@type": "hydra:PartialCollectionView",
    "hydra:first": "/serverapi/DroneCollection?page=1",
    "hydra:last": "/serverapi/DroneCollection?page=1"
  }
}
```

Here's the JSON-LD playground for this document: http://tinyurl.com/r2oje6q

The same applies to other responses, e.g. the `Drone` representation, which links to the same JSON-LD context as the collection leaving `MaxSpeed`, `Sensor`, `model` and `name` undefined:

```jsonc
// GET http://localhost:8080/serverapi/DroneCollection/9299bee8-bdc6-4d6f-9f48-f5884b3ef29c

{
  "@context": "/serverapi/contexts/DroneCollection.jsonld",
  "@id": "/serverapi/DroneCollection/9299bee8-bdc6-4d6f-9f48-f5884b3ef29c",
  "@type": "Drone",
  "MaxSpeed": "100",
  "Sensor": "Temperature",
  "model": "xyz",
  "name": "Drone 1"
}
```

### Steps to reproduce:
- Start the demo according to README
- Authenticate
- `GET http://localhost:8080/serverapi/DroneCollection`
- `GET http://localhost:8080/serverapi/contexts/DroneCollection.jsonld`
- Copy/paste both, document and context, into the JSON-LD playground (or click link above)

### Do you want to work on this issue?
no, I'm not familiar with python and only wanted to learn about Hydra.

**Comment by chrizandr** [comment]
Thank you for bringing this to our notice. You are right. 

Either we need to add a `hydra:` prefix or these identifiers need to explicitly be added to the context.

**Comment by Gs-001** [comment]
I'd like to try and work on this issue. Though I am not completely familiar with Hydrus but I'll try to catch up and I'll communicate if I get stuck somewhere.

**Comment by sameshl** [comment]
@chrizandr I have made the PR to fix this change https://github.com/HTTP-APIs/hydrus/pull/441.
This fix also required changes in the `python-hydra-core` 's `doc_maker` module, so I had to make this complementary PR https://github.com/HTTP-APIs/hydra-python-core/pull/34.

Let me know if any changes are required.

**Comment by sameshl** [comment]
@xadahiya This issue can be closed. Fixed with https://github.com/HTTP-APIs/hydrus/pull/441 and https://github.com/HTTP-APIs/hydra-python-core/pull/34
