### ISSUE TITLE
Authentication not working.

### ISSUE THREAD

**Issue by vedangj044** [HTTP-APIs/hydrus#430]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Running  `docker-compose up --build` creates the hydrus server, but when trying to login to access properties like `api/Area` with the default credentials, the alert box, either refreshes or the user has to click cancel.

### Expected Behaviour:

On entering the correct credential, user should be served with the default `Response 200` code.
else `failed to authenticate` message.

### Steps to reproduce:

Run server using
`docker-compose up --build`

then visit 
`http://localhost:8000/api/Area`

any property which requires authentication can be used to reproduce the error, not just "Area".

### Do you want to work on this issue?

YES.
I have retraced the error, the problem lies in `Check_nonce` method as it is unable to find `X-Authentication` header. It can't find the `X-Authentication` header as its the part of the response headers and is given after the page has been requested. We are trying to find those headers in "pending" state of the web page.

**Comment by Mec-iS** [comment]
Good. Please provide a [Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) when ready.

**Comment by xadahiya** [comment]
Authorization is working fine. Please follow this procedure http://www.hydraecosystem.org/Auth

The auth process is meant to be done by agents/bots that's why it is hard to do manually. Try the steps above and everything will work as expected. 
Thanks for your efforts. 😄
