### ISSUE TITLE
The URL of example API endpoint in README.md is incorrect.

### ISSUE THREAD

**Issue by PrathamDogra** [HTTP-APIs/hydrus#440]
### I'm submitting a 
- [X] bug report.
- [ ] feature request.

### Current Behaviour:

The endpoint given for the example API is http://localhost:8000/api/vocab which doesn't serve anything on **hydrus serve**.

### Expected Behaviour:

It should be(most probably) changed to http://localhost:8080/serverapi/vocab
### Do you want to work on this issue?

I would like to create a PR to resolve this issue.

**Comment by vedangj044** [comment]
In the README.md
It is mentioned that while using docker-compose, the server endpoint is `/api/vocab/`
and while using hydrus server it is `/serverapi/vocab` 
We can still change to `http://localhost:8080/serverapi/` to `http://localhost:8080/serverapi/vocab`

**Comment by chrizandr** [comment]
The `API_NAME` variable is what determines the URL for the API entrypoint.

- In case of the docker-compose demo a sample API is run with `API_NAME` set to "api".
- Running `hydrus serve` without specifying an `API_NAME` will choose the defualt entrypoint name. In this case `API_NAME` is set to "serverapi". 

The descriptions are correct. They are two different cases.
