### ISSUE TITLE
bug:hydrus cli takes any argument to start the server.

### ISSUE THREAD

**Issue by geekypandey** [HTTP-APIs/hydrus#451]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

The hydrus cli function is not properly implemented. 
hydrus takes any argument and starts serving.
e.g,
`hydrus serve`
`hydrus asdfasd `
both would do the same thing.

### Expected Behaviour:

`hydrus serve` should start the server and any sub command should not be considered.

### Steps to reproduce:

after setting up the environment,try
`hydrus serve` and
`hydrus asdfasdf`
both produces same effect.

### Do you want to work on this issue?

yes!! I have already found the solution. Can I submit the PR for the same?

**Comment by xadahiya** [comment]
Sure! Please go ahead

**Comment by geekypandey** [comment]
I had doubts in the implementation :
1. There is open parameter defined in document as `openapi` which is not being used anywhere and not even passed as argument. Sorry but I am not yet through whole hydrus implementation , just starting to understand so don't know if that is required.
2.The implementation idea is use **serve** as an subcommand of **hydrus cli** eg .,`hydrus serve`.
And the options will be passed to the this serve subcommand and not the main hydrus cli.
3.Could I bump up the version of Click to Click==7.0 which was previously at Click==6.7 to leverage new features? I will run the tests to make sure nothing is broken because of it.

Currently I have completed the implementation as specified above.

**Comment by sameshl** [comment]
@xadahiya Looks like this issue can be closed, seeing from PR https://github.com/HTTP-APIs/hydrus/pull/453
