### ISSUE TITLE
Outdated example code

### ISSUE THREAD

**Issue by sameshl** [HTTP-APIs/hydrus#454]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Lot of code for the `doc_gen.py` files from the hydrus repo in the .`/examples`  folder seem outdated.
For eg, The way the status codes is defined [here](https://github.com/HTTP-APIs/hydrus/blob/72b4cda49ab9cfe0fb775146e8d5113f5d6869e0/examples/drones/doc_gen.py#L59) is wrong. It get interpreted in the `expectsHeader` section instead of `possibleStatus` section. The correct way would have been to use the `HydraStatus` or `HydraError` class.

![Screenshot from 2020-02-23 22-26-11](https://user-images.githubusercontent.com/43701530/75365936-fb96b580-58e3-11ea-9a87-252cd78a918c.png)

### Expected Behaviour:

The expected result should have been that it gets added to the `possibleStatus` section.
![Screenshot from 2020-02-26 22-06-05](https://user-images.githubusercontent.com/43701530/75366220-66e08780-58e4-11ea-8276-1558b602d563.png)

### Steps to reproduce:

run `python3 hydrus/examples/drones/doc_gen.py` and examine the generated api doc and you would be able to find the above issues.
### Do you want to work on this issue?

Yes

**Comment by n1khilmane** [comment]
After running the `python3 hydrus/examples/drones/doc_gen.py`, I am getting this error, how should i fix it.
`File "doc_gen.py", line 3, in <module>
    from hydra_python_core.doc_writer import HydraDoc, HydraClass, HydraClassProp, HydraClassOp
ModuleNotFoundError: No module named 'hydra_python_core'
`

**Comment by sameshl** [comment]
@n1khilmane  Have you installed all the dependencies in your virtual envirnoment while setting up the project before running `python3 hydrus/examples/drones/doc_gen.py`? 

If not, in the root directory of this project: 
To create virtual env: `python3 -m venv venv`
To activate the env: `source venv/bin/activate`
To install the required dependencies: `pip3 install -r requirements.txt` 

Now run, `python3 hydrus/examples/drones/doc_gen.py`.
