### ISSUE TITLE
Examples Outdated

### ISSUE THREAD

**Issue by thrishik7** [HTTP-APIs/hydrus#455]
### Current Behaviour:
Examples in hydrus, for example in drones the doc isn't updated yet
` 

    "@type": "ApiDocumentation",

    "description": "API Documentation for the server side system",

    "possibleStatus": [],

    "supportedClass": [`

### Expected Behaviour:
the expected doc for drones  should be updated as shown below
` 

    "@type": "ApiDocumentation",

    "hydra:title": "API Doc for the server side API",

    "hydra:description": "API Documentation for the server side system",

    "hydra:supportedClass": []

    "hydra:possibleStatus": [] 
`
  `

### Do you want to work on this issue?
yes

**Comment by sameshl** [comment]
Related to https://github.com/HTTP-APIs/hydrus/issues/454

**Comment by Mec-iS** [comment]
duplicate #454
