### ISSUE TITLE
Migrate testsuite from unittest to pytest

### ISSUE THREAD

**Issue by sameshl** [HTTP-APIs/hydrus#460]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

The testsuite for hydrus is written using unittest library.
### Expected Behaviour:

@xadahiya  I feel that using pytest would greatly improve the readability of the test code with its features like fixtures, parameterisation, etc. As hydrus continues to develop and we continue to refactor it, I think this is an important point we might want to consider. The only disadvantage I feel using pytest is that it is not in the standard library.
### Do you want to work on this issue?

Yes

**Comment by xadahiya** [comment]
Sounds good! Please create a Pr

**Comment by Mec-iS** [comment]
I think it is a good improvement, it may speed up the automated test pipeline and allow more insight in the codebase for the purpose of a better proposal.

**Comment by sameshl** [comment]
@Mec-iS Yes you are right. I have already started working on it.

**Comment by Mec-iS** [comment]
please confirm that the number of tests executed by Travis in #466 are the same as in the old test machinery

**Comment by sameshl** [comment]
@Mec-iS Yes, I can confirm that the number of tests executed by Travis in #466 is same as the old test machinery. I am attaching some screenshots of the relevant parts of the build section so it becomes easier for you to see.

The first image is a screenshot of the travis CI build in #466 , it shows that the number of tests run are **54**:
![image](https://user-images.githubusercontent.com/43701530/80615424-499f7500-8a5d-11ea-9de3-979d97575943.png)

The second image is a screenshot of the travis CI build in #456, this one also shows that the number of tests run are **54**:
![image](https://user-images.githubusercontent.com/43701530/80615760-b581dd80-8a5d-11ea-869a-dad7dc757198.png)

Therefore, the number of tests executed by Travis is same in #466 as the old test machinery(54).
