### ISSUE TITLE
Possible mistake while refactoring

### ISSUE THREAD

**Issue by sameshl** [HTTP-APIs/hydrus#462]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

@xadahiya 
I came across this while I was refactoring hydrus.
I am referencing the commit https://github.com/HTTP-APIs/hydrus/commit/c0b492982b7093b38084d59afcfbbc52bb73d5e5#diff-57bc8a5a89375175a4bf37d573213377R353 
     
(by @de-sh )which is already merged.
In the changes to `hydrus/resources.py` under the POST method of the Item Collection class, line 353 the change made is 
```
headers_ = [{"Location": get_hydrus_server_url() + get_api_name() + "/" + path + "/"}]
```
to 
```
headers_ = [{"Location": "{}/{}/".format(get_hydrus_server_url(),get_api_name(),path)}]
```
### Expected Behaviour:

I think that there has been a mistake while refactoring as the `path` variable is not correctly used in the newly formated string. I think it should be (notice the extra `{}` in the string formating. 
```
headers_ = [{"Location": "{}{}/{}/".format(get_hydrus_server_url(),get_api_name(),path)}]
```
### Do you want to work on this issue?

Yes

**Comment by xadahiya** [comment]
Yes, you're right. Thank you
