### ISSUE TITLE
BUG: Possible error in tests

### ISSUE THREAD

**Issue by sameshl** [HTTP-APIs/hydrus#464]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

@xadahiya While migrating the test suite from unittest to pytest, I needed some clarification on a test which you had written.
While running this test  https://github.com/HTTP-APIs/hydrus/blob/72b4cda49ab9cfe0fb775146e8d5113f5d6869e0/hydrus/tests/test_auth.py#L83-L93 locally, I think I encountered a BUG. Correct me if I am wrong.
The `if` condition on line 88 in the code is never actually met(**meaning the `assert` statements are never executed!**). I used a debugger an found that the value of
`endpoints` is:
```
{'@context': '/demoapi/contexts/EntryPoint.jsonld',
 '@id': '/demoapi',
 '@type': 'EntryPoint',
 'anotherSingleClass': '/demoapi/anotherSingleClass',
 'dummyClassCollection': '/demoapi/DcTest',
 'extraClassCollection': '/demoapi/EcTest',
 'singleClass': '/demoapi/sc_path'}
```
while the value of `self.doc.collections` is:
```
{'DcTest': {'collection': <hydra_python_core.doc_writer.HydraCollection object at 0x7fee7add5518>, 'context': <hydra_python_core.doc_writer.Context object at 0x7fee7add5630>},
 'EcTest': {'collection': <hydra_python_core.doc_writer.HydraCollection object at 0x7fee7add5710>, 'context': <hydra_python_core.doc_writer.Context object at 0x7fee7add5828>}}
```
### Expected Behaviour:

The `if` condition is met and the `assert` statements are executed for testing the code.

I think the **required** iterator while testing for the `if` condition would have been,
```
    collection_names = [collection_object['collection'].name
                        for collection_object in doc.collections.values()]
```
in which `collection_names` has the value
```
['dummyClassCollection', 'extraClassCollection']
```
### Steps to reproduce:

* Insert a breakpoint before the `for` loop [here](https://github.com/HTTP-APIs/hydrus/blob/72b4cda49ab9cfe0fb775146e8d5113f5d6869e0/hydrus/tests/test_auth.py#L99)
* Execute the for loop with a debugger and see the execution never reaches the `assert` statements.
### Do you want to work on this issue?

Yes

**Comment by vddesai1871** [comment]
Yes, I had raised this issue earlier and solved it, but I think I had missed this whole file(don't know how). 
Regarding the solution, I would advise using the approach we have used in other test files(https://github.com/HTTP-APIs/hydrus/blob/72b4cda49ab9cfe0fb775146e8d5113f5d6869e0/hydrus/tests/test_app.py#L193).

**Comment by sameshl** [comment]
Ok cool. I have anyway started with my approach mentioned above. Will be easy to switch to the approach mentioned by you.

**Comment by sameshl** [comment]
This bug was resolved by what @vddesai1871 said.
