### ISSUE TITLE
Research possible improvements for the models and architecture

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#47]
Based on the papers enlisted in Gitter channel, define possible evolution for Hydrus as a mature Web server.

https://arxiv.org/abs/1610.06264
https://arxiv.org/abs/1603.04068
http://arxiv.org/abs/1701.05397 
http://arxiv.org/abs/1707.06507

[UPDATE] 
http://redisgraph.io/design/
Introduction and paper here: https://redis.io/topics/indexes#representing-and-querying-graphs-using-an-hexastore

**Comment by tibi77** [comment]
The solution of this issue should be a prediction of some sorts or a paper with possibilities of development and some ideas how they can be achieved?

**Comment by Mec-iS** [comment]
Yea a design proposal would be great, but first it is needed a broad understanding about how `hydrus` has been designed and is working.

**Comment by Mec-iS** [comment]
The general architecture has taken shape as in https://github.com/HTTP-APIs/hydra-ecosystem-wiki/blob/master/Design.md

**Comment by Mec-iS** [comment]
Architecture for server-side (`hydrus`) has been stabilised to SQL-based REST. Most of work moves to client-side (`python-hydra-agent`) with the current [GSOC tasks](https://github.com/HTTP-APIs/python-hydra-agent/labels/GSOC-2018).

**Comment by Mec-iS** [comment]
A system for unique ids for instances have to be established.

**Comment by Mec-iS** [comment]
> A system for unique ids for instances have to be established.
Done using UUID, server-level uniqueness guaranteed.

**Comment by Mec-iS** [comment]
Next big challenges for GSOC 2019:
* allow a client to connect to different servers and build a "network-level" graph
* establish a synchronization protocol (using `WebPubSub`?) between clients and servers.

**Comment by Mec-iS** [comment]
You can start collecting some examples of Gossip over HTTP. We are also looking to implement a protocol for server-agent data synchronization >>> https://github.com/HTTP-APIs/hydrus/issues/300
basically an agent should be notified to update its data graph when an update happens in hydrus.

**Comment by Mec-iS** [comment]
@invinciblycool just a note: as Hydra is a W3C draft we have some wish of using other W3C standards to where possible. that's why I suggested [WebSub](https://www.w3.org/TR/websub/)

**Comment by invinciblycool** [comment]
Makes sense, WebSub is great to start with.

**Comment by invinciblycool** [comment]
https://github.com/andymccurdy/redis-py#publish--subscribe can definitely be considered.
