### ISSUE TITLE
[DISCUSSION] Foreign keys implementation in new database schema

### ISSUE THREAD

**Issue by sameshl** [HTTP-APIs/hydrus#480]
@xadahiya @chrizandr 
The current problem we have is how the foreign key relationship between resources has to be implemented in the new database schema in which we are going to have a table for each resource.

For example, in the supported Properties of the `Drone` class, we have a reference to the `State` class. This implies that there is a foreign key relationship between the `Drone` class and the `State` class.
```python
           "supportedProperty": [
               {
                   "@type": "SupportedProperty",
                   "property": "vocab:State",
                   "readable": "false",
                   "required": "true",
                   "title": "DroneState",
                   "writeable": "false"
               },
```
The `State` class for reference:
```python
       {
           "@id": "vocab:State",
           "@type": "hydra:Class",
           "description": "Class for drone state objects",
           "supportedOperation": [
               {
            ....
            ....
           ],
           "supportedProperty": [
               {
                   "@type": "SupportedProperty",
                   "property": "http://auto.schema.org/speed",
                   "readable": "false",
                   "required": "true",
                   "title": "Speed",
                   "writeable": "false"
               },
        ....
        ....
               {
                   "@type": "SupportedProperty",
                   "property": "http://schema.org/identifier",
                   "readable": "false",
                   "required": "true",
                   "title": "DroneID",
                   "writeable": "false"
               }
           ],
           "title": "State"
       }
```
Now, we need to decide on the details of the foreign key implementation.
I basically needed clarification in two aspects:
1. The foreign key column implementation
2. Finding the foreign key relationship from the ApiDoc

**Regarding the foreign key column:**
I have thought of three possible ways we could do this:
* We could have a column named **DroneState**(name taken from the `title` attribute of that supported property) in the `Drone` table itself as the foreign key relationship was mentioned in the `Drone` class itself  (which holds the `id` of the State instance from the `State` table of that particular drone)
* We could have a `FK_State` column in the `Drone` table (which holds the `id` of the State instance from the `State` table of that particular drone)
* We could have a `FK_Drone` column in the `State` table(which holds the `id` of the Drone instance from the `Drone` table of that particular drone).

**Let me know which of the above three approaches have to be taken, or any other better approach which you suggest.**

**Note:** I have named the columns `FK_State` and `FK_Drone` from my own convention in which I would name the foreign key columns as `FK_ForeignTableName` in the table in which I am storing the foreign keys. Let me know if you have any better suggestion on naming the columns or I should keep it like this itself.

--------------------------------------------------------------------------------------------------------------------------------------

**Regarding finding the foreign key relationship from the ApiDoc:**
I wanted to confirm my algorithm I will use to determine if any property (in `supportedProperty` of any resource in the ApiDoc) is just another property which needs to have a regular column or it should act as a foreign key to another table.

What I was thinking of was:
* checking the value of the `property` attribute of that property.
* If the value of the `property` value does not have `http` in it, it would mean that the property is not linking to any `http://schema` definition. Which implies that the property is linking to any other resource in the same ApiDoc( and acting as a foreign key).
* Then I will parse the value (of the `property` attribute) and find the name of the resource (table) the property is pointing to and acting as a foreign key.
* Parsing will be done by splitting the value of the `property` attribute at `vocab:` and consider everything after that as the table name for foreign key relationship.
* Then I will make that relationship of foreign key between the two tables.

Let's take an example to understand this better:
These are the supported properties under the `Drone` class in the ApiDoc:
```python
           "supportedProperty": [
               {
                   "@type": "SupportedProperty",
                   "property": "vocab:State",
                   "readable": "false",
                   "required": "true",
                   "title": "DroneState",
                   "writeable": "false"
               },
               {
                   "@type": "SupportedProperty",
                   "property": "http://schema.org/name",
                   "readable": "false",
                   "required": "true",
                   "title": "name",
                   "writeable": "false"
               },
               {
                   "@type": "SupportedProperty",
                   "property": "http://schema.org/model",
                   "readable": "false",
                   "required": "true",
                   "title": "model",
                   "writeable": "false"
               },
               {
                   "@type": "SupportedProperty",
                   "property": "http://auto.schema.org/speed",
                   "readable": "false",
                   "required": "true",
                   "title": "MaxSpeed",
                   "writeable": "false"
               },
               {
                   "@type": "SupportedProperty",
                   "property": "http://schema.org/device",
                   "readable": "false",
                   "required": "true",
                   "title": "Sensor",
                   "writeable": "false"
               }
           ],
```
Out of these, only the first one, with `title` attribute as  **DroneState** does not have `http` in it’s `property` attribute. That confirms that it is trying to establish a foreign key relationship with a table for another resource. The name of that table will be found from the `property` attribute itself. I will split the value of the `property` attribute at `vocab:` and consider everything after that as the table name. In this case, it turns out to be `State`. And then, I will establish a foreign key relationship between the Drone table and the State table.

**Let me know if this algorithm is fine for differentiating a property if it is acting as a foreign key to another resource(table) or just another property.**

**Comment by chrizandr** [comment]
Combine this discussion and the details of your final approach into a doc, we can use that to add documentation to the website.

**Comment by sameshl** [comment]
@chrizandr Okay, will do

**Comment by sameshl** [comment]
> Combine this discussion and the details of your final approach into a doc, we can use that to add documentation to the website.

Added docs on database design in https://github.com/HTTP-APIs/hydrus/pull/495. Therefore this issue can be closed.
