### ISSUE TITLE
hydrus hardcoded with 'vocab:' to check foreign key relationship

### ISSUE THREAD

**Issue by sameshl** [HTTP-APIs/hydrus#482]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

At the moment, `hydrus` has been hardcoded with `vocab:` while it tries to identify foreign key relationship. For eg, [here](https://github.com/HTTP-APIs/hydrus/blob/27db73939f2fe8a8d08a8e3c2096876247dcf7d0/hydrus/data/db_models.py#L90).

@chrizandr  suggested we also include the case where we expand the `vocab:` keyword and also check that for identifying foreign key relationship. For eg, something like https://www.markus-lanthaler.com/hydra/event-api/vocab#Class1.

But the problem here is that just expanding `vocab:` won't solve the underlying issue for discovering all foreign key relationships correctly. For example, we could as well have something called `myownvocab:` in `@context` node of the Hydra API doc and then that could be used to reference something like `myownvocab:Class1`.

We might also extract this correctly after some work at parsing the API doc. But if suppose our context becomes nested, it will become difficult to parse.

### Expected Behaviour:

The ideal behaviour should be that, `hydrus` starts with an expanded API doc. We should not parse the API doc without expanding it beforehand. This change should then ideally take place it the `hydra_python_core` library, which generates the API doc object which `hydrus` uses for parsing data required of the API doc. Therefore the output of the `hydra_python_core` libraries `doc_maker` module should be an API doc which is expanded beforehand.

**Comment by chrizandr** [comment]
Open the relevant issu in the core library as well.

**Comment by sameshl** [comment]
> Reference the relevant issue in the core library as well.

This issue is related to https://github.com/HTTP-APIs/hydra-python-core/issues/38

**Comment by chrizandr** [comment]
@sameshl Close if done.

**Comment by sameshl** [comment]
@chrizandr I am working on this issue atm. Will close when done :+1:
