### ISSUE TITLE
ModuleNotFoundError: No module named 'pip.req' when running setup.py

### ISSUE THREAD

**Issue by kshitij86** [HTTP-APIs/hydrus#499]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
I am trying to run hydrus on my machine.
I cloned the repo, installed all packages using requirements.txt in a virtualenv. When I run ```python3 setup.py``` install I get the following error:]
```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from pip._internal.download import PipSession
ModuleNotFoundError: No module named 'pip._internal.download'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
```

I am using Python > 3.6.0 and the latest pip.

### Expected Behaviour:
It should install hydrus on my machine.

### Steps to reproduce:
1. Cloned the repo
2. Run ```python3 setup.py```

### Do you want to work on this issue?
Yes

**Comment by kshitij86** [comment]
@chrizandr I would like to work on a fix to this issue.

**Comment by kshitij86** [comment]
Users [have had this issue already](https://github.com/HTTP-APIs/hydrus/issues/439), but the official Hydrus repo is not updated to reflect or correct that.

**Comment by sameshl** [comment]
This issue has been fixed by https://github.com/HTTP-APIs/hydrus/pull/500.
