### ISSUE TITLE
Independent server and client

### ISSUE THREAD

**Issue by pchampin** [HTTP-APIs/hydrus#5]
In #2, @Mec-iS wrote
>     A HYDRA server that can serve data and metadata to a client (this layer can be split into a traditional lower level server relying on a graph database plus a "HYDRA middleware"),
>     A client that can "understand" HYDRA metadata and connect to HYDRA-enabled services, and possibly "learn and remember" about past interactions with other services to store its own set of concepts to be used in the usage's domain.

I think we *must* insist on developing the client and server as independently as possible. Ideally, different people would work on each part. If we end up with tightly coupled client and server, we will fail to demonstrate the value of Hydra.

**Comment by Mec-iS** [comment]
@pchampin Yeah, that is the idea. I started from a functional approach, so ideally even single features/functions of each of them (server and client) can be though as independent (different midllewares in the same server/pipe). The idea was to have a distributed architecture of different services using queueing and/or multistreaming. Let's strike the right balance for integration.

For the server we have a pretty defined starting point with the spec and Levanzo. For the client it will be probably an even more complicated task (Space Is Hard! (: ) and I have already some ideas ready to make it integrated with prediction-based and, in general, machine-learning libraries.

For now I think, to make everybody comfortable with the spec, we should focus on the server implementation. This way we can fully understand the features we are going to leverage, and when GSOC starts we will have all the material ready to start also with the client.

**Comment by Mec-iS** [comment]
[USEFUL LINK] For a very good implementation of a Web server for APIs, take a look to [HUG](https://github.com/timothycrosley/hug)

**Comment by pchampin** [comment]
Very nice, indeed!
Having HUG automatically generate a Hydra documentation would be really
cool...
