### ISSUE TITLE
Add Drone Collection in the sample API DOC

### ISSUE THREAD

**Issue by priyanshunayan** [HTTP-APIs/hydrus#501]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

In the sample [hydra doc](https://github.com/HTTP-APIs/hydrus/blob/master/hydrus/samples/hydra_doc_sample.py) Drone Collection is missing. The doc contains the Drone class already, so it would be nice to have Drone Collection also in the api doc. 

### Expected Behaviour:

The Drone Collection should be a part of the API DOC. 

### Steps to reproduce:

Go through the sample doc: https://github.com/HTTP-APIs/hydrus/blob/master/hydrus/samples/hydra_doc_sample.py

### Do you want to work on this issue?

no

**Comment by som23ya** [comment]
Can I work on this? I would be happy to have some guidance on how to start.

**Comment by priyanshunayan** [comment]
@som23ya You might want to see [how other collections are generated](https://github.com/HTTP-APIs/hydrus/blob/master/examples/drones/doc_gen.py#L237) and subsequently add the required code for generating DroneCollection. Also, we want to update [this doc](https://github.com/HTTP-APIs/hydrus/blob/master/examples/drones/doc.py) and [this doc ](https://github.com/HTTP-APIs/hydrus/blob/master/hydrus/samples/hydra_doc_sample.py) with the new generated code.

**Comment by raoashish10** [comment]
@priyanshunayan I was looking into this issue and I can saw that there is a command for creating the DroneCollection in the doc_gen.py file which already exists. 
``` 
drone_collection = HydraCollection(collection_name="DroneCollection",
                                         collection_description="A collection of drones",
                                         manages=drone_collection_manages)
``` 
I am a little confused about the issue as the command to add the supported operations is also present in the file. 
However, I have added the JSON-LD code that I think is expected in the hydra_doc_sample.py file. If you could just clarify if this is what is to done, it would be great and then I will submit a PR for review

**Comment by priyanshunayan** [comment]
@raoashish10 Somehow `message_collection` is being added twice [L253](https://github.com/HTTP-APIs/hydrus/blob/master/examples/drones/doc_gen.py#L253) and [L242](https://github.com/HTTP-APIs/hydrus/blob/master/examples/drones/doc_gen.py#L242). So, I think replacing [L242](https://github.com/HTTP-APIs/hydrus/blob/master/examples/drones/doc_gen.py#L242) with `drone_collection` and executing this module will generate an updated doc which can be used to update [/examples/doc](https://github.com/HTTP-APIs/hydrus/blob/master/examples/drones/doc.py) and [/samples/doc](https://github.com/HTTP-APIs/hydrus/blob/master/hydrus/samples/hydra_doc_sample.py).

**Comment by raoashish10** [comment]
@priyanshunayan Got it! I'll fix it now
