### ISSUE TITLE
DOC: Add tutorials on using hydrus in documentation

### ISSUE THREAD

**Issue by sameshl** [HTTP-APIs/hydrus#504]
We need to try to add more tutorial-like examples in our documentation for developing APIs using `hydrus`. Something like projects like Matplotlib have [here](https://matplotlib.org/3.3.1/tutorials/index.html).

Right now, I think we have one [on the main website](https://www.hydraecosystem.org/01-Usage).

But, I think it will be better to add more tutorials on using `hydrus` as that would really help newcomers to start using it without much effort.

**Comment by Purvanshsingh** [comment]
@sameshl this issue is still showing open, resolved with #516
