### ISSUE TITLE
psycopg2 gives an error on building 

### ISSUE THREAD

**Issue by raoashish10** [HTTP-APIs/hydrus#505]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Installation of hydrus failed on building due to an error regarding the psycopg2 module.
Versions:
Python Version: [3.8.3]
pip version: 20.2.3

Platform: 
Windows 10. Used a virtual environment (Python 3.8.3) for installation of hydrus. 

Error Log:
```psycopgmodule.c
psycopgmodule.c(689): error 2037: left of 'next' specifies undefined struct/union '_is'
psycopgmodule.c(690): error 2037: left of 'next' specifies undefined struct/union '_is'
```
### Expected Behaviour:

There should be no error while installation of hydrus
### Steps to reproduce:

1. Clone the hydrus repo
2. Run the command ```python setup.py install```
### Do you want to work on this issue?

no

**Comment by chrizandr** [comment]
From what I read online, it seems like you need the python-dev module to compile the C/C++ code needed to install the module. 

Do you have python-dev installed?

**Comment by chrizandr** [comment]
Issue has been resolved
