### ISSUE TITLE
IRI missing domain name

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#507]
### I'm submitting a 
- [ x] bug report.
- [ ] feature request.

### Current Behaviour:
Every IRI in the API should be a complete IRI to be dereferenced. For example:
```
{
  "@context": "/serverapi/contexts/DatastreamCollection.jsonld",
  "@id": "/serverapi/DatastreamCollection/",
  "@type": "DatastreamCollection",
  "hydra:totalItems": 0,
  "hydra:view": {
     "@id": "/serverapi/DatastreamCollection?page=1",
    "@type": "hydra:PartialCollectionView",
    "hydra:first": "/serverapi/DatastreamCollection?page=1",
    "hydra:last": "/serverapi/DatastreamCollection?page=1"
},
...
```
All paths starting with `/...` should start with `http://localhost:8000/...` so that the link can be followed by clicking/reading/dereferencing the string.

### Expected Behaviour:
```
{
  "@context": "http://localhost:8000/serverapi/contexts/DatastreamCollection.jsonld",
  "@id": "http://localhost:8000/serverapi/DatastreamCollection/",
  "@type": "DatastreamCollection",
  "hydra:totalItems": 0,
  "hydra:view": {
     "@id": "http://localhost:8000/serverapi/DatastreamCollection?page=1",
    "@type": "hydra:PartialCollectionView",
    "hydra:first": "http://localhost:8000/serverapi/DatastreamCollection?page=1",
    "hydra:last": "http://localhost:8000/serverapi/DatastreamCollection?page=1"
},
...
```
Having a `HOST_DOMAIN` global variable that has default to `http://localhost:port` would be fine.

**Comment by codeboy5** [comment]
Hey can I take this up ?

**Comment by sameshl** [comment]
@codeboy5 Yes, go ahead!

**Comment by codeboy5** [comment]
Hey can you also tell me which file should i look at to make the required changes ?

**Comment by raoashish10** [comment]
If this issue is not being worked on and also isn't assigned, I would like to take this up

**Comment by raoashish10** [comment]
@Mec-iS Correct me if I am wrong but I think changes should be made in the hydra_python_core repo for this issue because changes are required in the content of the doc that is returned and making changes in the hydra_python_core repo would be much more convenient

**Comment by farazkhanfk7** [comment]
If this issue is not assigned to anyone. Can I work on this ?

**Comment by priyanshunayan** [comment]
I am getting the response with missing domain name in the `@id` field when making GET on /<classendpoint>/<id> or on /<collectionendpoint>/id. 
Screenshots: 
Collection Endpoint: 
![image](https://user-images.githubusercontent.com/32892545/105708440-80e27a00-5f3a-11eb-9e3e-8816a994c32a.png)
Class Endpont:
![image](https://user-images.githubusercontent.com/32892545/105708536-9f487580-5f3a-11eb-97e1-9293bf79de88.png)

**Comment by Mec-iS** [comment]
@priyanshunayan have you dropped and reinstalled the libraries to the the latest versions?

**Comment by priyanshunayan** [comment]
Yes, I have.

**Comment by farazkhanfk7** [comment]
@priyanshunayan  Thanks for catching that. Looks like I missed the part where we I had to add host name in crud.py as well. I'll submit a PR with new changes asap.

**Comment by khabdrick** [comment]
This issue is showing open, is it actually open @Mec-iS
