### ISSUE TITLE
/serverapi/DroneCollection returns 404

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#509]
### I'm submitting a 
- [x ] bug report.
- [ ] feature request.

### Current Behaviour:
http://localhost:8080/serverapi/DroneCollection does not return the collection

### Expected Behaviour:
It should return all DroneCollection metadata and members

**Comment by chrizandr** [comment]
Could this also be because of a similar problem as #510 .

Can someone confirm if it is working or not?

**Comment by priyanshunayan** [comment]
@chrizandr fixed via #511 👍
