### ISSUE TITLE
/serverapi/contexts/EntryPoint.jsonld returns 404

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#510]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
`/serverapi/contexts/EntryPoint.jsonld` should return a JSON-LD object

**Comment by raoashish10** [comment]
@Mec-iS I tried looking into this bug but I am getting a JSON-LD object. I mean I am not getting a 404 error.

**Comment by Mec-iS** [comment]
Right. I don't know which problem did not allow my local env to reach it.
