### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by harshraj22** [HTTP-APIs/hydrus#523]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
Gives error while installing dependencies using `pip3 install -r requirements.txt`

### Expected Behaviour:
clean installation without any issues

### Steps to reproduce:
create a new virtualenv (`virtualenv -p python3 hydra-env`) and activate it, then install dependencies using `pip3 install -r requirements.txt`

### Screenshot:
![hydrous-installation](https://user-images.githubusercontent.com/46635452/98075675-cdb23980-1e92-11eb-8454-3d23be1386e6.png)

**Comment by harshraj22** [comment]
ps. similar issue was reported [here](https://github.com/HTTP-APIs/hydrus/issues/379#issuecomment-688452960)

**Comment by Mec-iS** [comment]
which instructions in the README did you follow? Have you tried alternative installation modes?

**Comment by Mec-iS** [comment]
@priyanshunayan please take a loot when you have time

**Comment by harshraj22** [comment]
@Mec-iS  I followed the installation process in README below the [demo](https://github.com/HTTP-APIs/hydrus#demo) header

**Comment by priyanshunayan** [comment]
@harshraj22 Can you share the python and pip versions you are using?

**Comment by harshraj22** [comment]
![hydrous-debug](https://user-images.githubusercontent.com/46635452/98697438-ee025c80-239a-11eb-8e84-3e0cbf9f5d54.png)

@priyanshunayan is this what you asked for ?

**Comment by priyanshunayan** [comment]
@harshraj22 Unfortunately, I am not able to reproduce this error, despite using the same python and pip version. Is there any specific reason you prefer `virtualenv` instead of  recommended `venv`?

**Comment by harshraj22** [comment]
Nothing specific. Just that I am more comfortable with `virtualenv`. Anyway, I'll try with `venv`.

**Comment by vasharma05** [comment]
I also have the same versions and I am also getting the same error, what to do?

**Comment by harshraj22** [comment]
@vasharma05 I couldn't get that fixed, so I abandoned the idea of trying it. Probably @priyanshunayan  can help ? Feel free to Reopen this issue in that case.
