### ISSUE TITLE
Add fields for python and pip versions along with OS details in the issue template. 

### ISSUE THREAD

**Issue by priyanshunayan** [HTTP-APIs/hydrus#526]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Without knowing exactly the python, pip and OS details, it's very difficult to reproduce the errors. 
### Expected Behaviour:

Having them in the issue template will help to reproduce bugs faster. 
### Do you want to work on this issue?

yes

**Comment by Purvanshsingh** [comment]
@priyanshunayan Please do review the Pull Request.

**Comment by priyanshunayan** [comment]
Issue resolved via #529
