### ISSUE TITLE
Psycopg2 python3.8 compatibility issue

### ISSUE THREAD

**Issue by king-11** [HTTP-APIs/hydrus#530]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

pspcopg2==2.7.5 doesn't support python3.8 [Link](https://github.com/archlinux/archweb/issues/259)

### Expected Behaviour:

Dependencies should install smoothly with all versions of python

### Steps to reproduce:

Try installing dependencies with python3.8 either through 
```bash
pip3 install -r requirements.txt
```
or
```bash
poetry install
```

### Do you want to work on this issue?

yes

**Comment by raoashish10** [comment]
Try using python 3.7. I think the issue is with the psycopg2 module only. Even the docker image is using python 3.7. I believe the maintainers of psycopg2 haven't resolved the issue yet for python 3.8. Not too sure though but I had the same error when I was installing.

**Comment by king-11** [comment]
They have resolved the issue actually we have to update the dependency

**Comment by Mec-iS** [comment]
thanks for finding out. please open a PR
