### ISSUE TITLE
Enhancing Code: Simple Refactoring

### ISSUE THREAD

**Issue by harshraj22** [HTTP-APIs/hydrus#534]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
Works perfectly. Though, results in a score of -2.74 out of 10 when using [pylint](https://www.pylint.org/)

### Expected Behaviour:
Would have a higher score when used pylint. This would ensure code quality is high.

### Screenshots:
![a](https://user-images.githubusercontent.com/46635452/102326312-46d0a080-3faa-11eb-94ac-9c22f17350d0.png)

### Steps to reproduce:
Run: `python3 -m pylint cli.py`

### Do you want to work on this issue?
yes

**Comment by harshraj22** [comment]
@chrizandr should I create a pull request enhancing the code ? Can you assign me this issue ?

**Comment by chrizandr** [comment]
Pylint has a lot of unnecessary rules that are difficult to maintain. We tried using pylint before but it was too much of a hassle so the idea was left. See #312

**Comment by harshraj22** [comment]
Alright :)
