### ISSUE TITLE
Create Proper Documentation for developement

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#54]
see https://github.com/HTTP-APIs/hydrus/issues/11#issuecomment-318720133

**Comment by chrizandr** [comment]
Walkthrough added in Usage section of Wiki. https://github.com/HTTP-APIs/hydrus/wiki/Usage

**Comment by Mec-iS** [comment]
The walk-through is still too verbose. Move all the extensive documentation to an "Architectural Design" page. A new "Usage/Walk-Thorugh" page should have few lines and concise numbered list of steps to add the hydra vocabulary and run the server. Something like:
1. Familiarize with Hydra Spec and examples (a list of material to learn Hydra)
2. Add your custom made Hydra vocabulary to the file my_hydra.py (having an "How To Write Your Own Hydra API" post would be great)
3. Run the server as explained in README
To

**Comment by chrizandr** [comment]
New issue created as #72
