### ISSUE TITLE
Fix dead code in authentication tests

### ISSUE THREAD

**Issue by farazkhanfk7** [HTTP-APIs/hydrus#544]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Found a minor issue with some tests in **_test_auth.py_**. 
https://github.com/HTTP-APIs/hydrus/blob/e15d18e9f7b535814ef3a2f981be443896206adb/hydrus/tests/functional/test_auth.py#L49-L64

_doc_writer_sample.py_ is used to generate _apidoc_ for test_auth. 
The endpoints variable here holds '`@context', '@id', '@type', 'anotherSingleClass', 'collections', 'dummyClass', 'singleClass'`  and collection_names  returns the a list of two collections `['Extraclasses', 'dummyclasses'] `. So basically the `if endpoint in collection_names` condition here is never met and **assert** statement won't be executed, turning it into some kind of dead code. A [similar issue](https://github.com/HTTP-APIs/hydrus/issues/464) has been raised before when tests were written in unittest instead of pytest,but it's closed and was left unresolved.

### Expected Behaviour:

The **assert** statements should be executed, so that the status code of response can be checked.
### Steps to reproduce:

Use a debugging tool and insert a breakpoint at `for` and `if` condition.
### Environment:
 
* python version : 3.6.9
* pip version :  20.2.2
* OS details : Ubuntu 20.04

### Do you want to work on this issue?

**Yes**

**Comment by sameshl** [comment]
Great catch @farazkhanfk7! :rocket: 
I don't know how I missed that condition while refactoring. :sweat_smile:

**Comment by Mec-iS** [comment]
merged
