### ISSUE TITLE
psycopg2==2.8.6 giving error in installation.

### ISSUE THREAD

**Issue by Purvanshsingh** [HTTP-APIs/hydrus#546]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
psycopg2==2.8.6 is hydrus dependency giving error on installation.

### Expected Behaviour:

should be updated with stable version according to https://www.psycopg.org/docs/install.html ( psycopg2-binary )

### Steps to reproduce:
pip install -r requirement.txt

### Snapshot:

![Screenshot from 2021-01-14 14-26-29](https://user-images.githubusercontent.com/49719371/104567234-93280280-5674-11eb-894d-30d8a2cfd85c.png)

### Environment:
 
* python version 3.6.12
* pip version 20.3.3
* OS details ubuntu 20.04 LTS

### Do you want to work on this issue?

yes

**Comment by king-11** [comment]
@Purvanshsingh are using any virtual environment ?

**Comment by Purvanshsingh** [comment]
@king-11 yes,
![Screenshot from 2021-01-14 14-56-02](https://user-images.githubusercontent.com/49719371/104571089-b6ed4780-5678-11eb-9d00-9abc3ae771d5.png)

**Comment by king-11** [comment]
![Screenshot_20210114_145944](https://user-images.githubusercontent.com/52061363/104571542-38dd7080-5679-11eb-8547-d912c1dac9bc.png)

**Comment by king-11** [comment]
if you can try clearing your virtualenv cache and set it up again maybe that can help because with same version the app just works fine and even the build is passing as I said

**Comment by Purvanshsingh** [comment]
My concern is even if installing `pip install psycopg2==2.8.6` separately giving error can you confirm this?
![Screenshot from 2021-01-14 15-06-50](https://user-images.githubusercontent.com/49719371/104572928-4e9f6580-567a-11eb-90f6-bfcf6d2ce17a.png)

**Comment by king-11** [comment]
I can confirm this error didn't error it seems to me you are using anaconda for your virtual environment and there are conflicting binaries due to which the install isn't occurring properly you can set up your virtualenv using poetry too, try that because it is a conflicting binary issue

**Comment by king-11** [comment]
![Screenshot_20210114_151836](https://user-images.githubusercontent.com/52061363/104574260-d33eb380-567b-11eb-9750-881bdc4d4995.png)

**Comment by Purvanshsingh** [comment]
> I can confirm this error didn't error show up..... it seems to me you are using anaconda for your virtual environment and there are conflicting binaries due to which the install isn't occurring properly you can set up your virtualenv using poetry too, try that because it is a conflicting binary issue

yes, I was using conda virtual environment, Will try it with poetry. thanks :-)

**Comment by Purvanshsingh** [comment]
@king-11 in your screenshot you have already installed `psycopg2==2.8.6` can please uninstall and install it again?
I think may be the the issue is from their side, I tried with python virtualenv as well still getting the same error.

**Comment by king-11** [comment]
![Screenshot_20210114_173015](https://user-images.githubusercontent.com/52061363/104588326-346f8280-568e-11eb-8923-db2dbbcf748b.png)
Actually, my system and the Travis checks are working so there can't be any such issue here. Moreover, I formatted my virtual env and then installed again with the updated upstream seems to work without any issue. So I am not able to replicate your issue right now

**Comment by sameshl** [comment]
@king-11 So, can you confirm that this is not an issue?

**Comment by king-11** [comment]
> @king-11 So, can you confirm that this is not an issue?

I have tried replicating it my wiping my enviornment but there doesn't seem to be any issue with installation anyway in both python 3.6.12 and above till python 3.8 too

**Comment by Purvanshsingh** [comment]
Hey, @sameshl I have switched to ubutntu 20.04 so I was setting the working environment again there I faced this issue.
I am not sure but according the screenshot @king-11 send his system is using the cache to install `psycopg2==2.8.6`
due to that it may be working.
![Screenshot from 2021-01-14 19-49-21](https://user-images.githubusercontent.com/49719371/104603128-2166ad80-56a2-11eb-9740-65644c2ff01d.png)

I request you to try to installing it with `pip install --no-cache-dir psycopg2==2.8.6`

**Comment by Purvanshsingh** [comment]
I have solved the issue for ubuntu ( https://stackoverflow.com/questions/11618898/pg-config-executable-not-found ),

`sudo apt-get install libpq-dev`

pg_config is in postgresql-devel (libpq-dev in Debian/Ubuntu, libpq-devel on Centos/Cygwin/Babun.)

**Comment by king-11** [comment]
seems like was an os issue instead of dependency one 🤔

**Comment by Purvanshsingh** [comment]
> seems like was an os issue instead of dependency one  and cache or fresh didn't cause the issue  I tried with it too

@king-11, ya I think the same, but its good to know so that if anyone face the issue we can suggest them,
or we can add it in documentation if you are using lunix/ubuntu `libpq-dev` this dependency should install prior.

**Comment by Mec-iS** [comment]
solved. `psycopg` requires proper system-dependant library. check `psycopg` documentation for details.
