### ISSUE TITLE
Sphinx Documentation folder must be added 

### ISSUE THREAD

**Issue by raoashish10** [HTTP-APIs/hydrus#551]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Currently the sphinx documentation of the hydrus module is in another repository. The documentation has a requirement that it needs to be placed in the hydrus repo and that can only be done locally. Since we are updating the docs, the documentation folder can be added in this repository so that the readthedocs page (https://hydrus.readthedocs.io/en/latest/index.html) can be updated and the sphinx documentation can be fetched into the modules section of the new documentation (I am working on this [PR](https://github.com/HTTP-APIs/docs/pull/9)).
### Expected Behaviour:

Doc folder from the repo https://github.com/HTTP-APIs/documentation-hydrus can be shifted into this repo.

**Comment by Mec-iS** [comment]
Good idea but as the API is not stable yet, it would not be very helpful for now.
Closing it and maybe reopening after hydrus version 1.0
