### ISSUE TITLE
Avoid insertion of duplicate members in a collection

### ISSUE THREAD

**Issue by farazkhanfk7** [HTTP-APIs/hydrus#555]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Currently, a member with the same ID can be added multiple times in the same collection.
### Expected Behaviour:

Member ID in Collection database table should be unique and hydrus should raise and handle the integrity error everytime an object with existing ID is inserted in a collection. A response with 400 (Bad Request) code should be returned instead of a server error.

### Steps to reproduce:

- Make a PUT request to a Collection endpoint : `http://localhost:8080/serverapi/<collection_name>/<collection-id>`
- Insert an object again with same Object ID in JSON body using PUT request.

### Environment:
 
* python version
* pip version
* OS details

### Do you want to work on this issue?

Yes

**Comment by b-thebest** [comment]
This issue is still active?

**Comment by Mec-iS** [comment]
we have to work out #554

**Comment by farazkhanfk7** [comment]
Fixed with #556 .Can be closed.
