### ISSUE TITLE
Backend choice

### ISSUE THREAD

**Issue by pchampin** [HTTP-APIs/hydrus#6]
In #2, @Mec-iS wrote:
> At first impression I would avoid Triple Stores and try to use a Graph Database or try to prototype something with Apache TinkerPop or also Spark GraphX, to gain in flexibility to switch to different solutions.

I tend to disagree. JSON-LD uses JSON as its concrete syntax, and RDF as its abstract syntax (i.e. data model), so the most natural fits would be either
* a triple-store (fitting the abstract syntax), or
* a document-oriented database (fitting the concrete syntax -- see http://greggkellogg.net/2012/08/json-ld-and-mongodb/)

**Comment by Mec-iS** [comment]
@pchampin I would prefer MongoDB as a solution because it is something I have been using a lot, but it has always been told to me (at least until two years ago) that reasoning on that it is pretty impossible and there is no SPARQL endpoint that can do it (using SPARQL is not my priority for sure, but everybody I have talked to was pretty much convinced that that is no real alternative). Can you extend your proposal to include other libraries involved in a MongoDB-based stack to have the full picture?

**Comment by pchampin** [comment]
I would not be so radical about providing a SPARQL endpoint, especially if we supplement it with a Triple Pattern Fragment service...

Regarding reasoning, the problem with document-based DBs is that they work with JSON structure, so from the point of view of RDF/Linked Data, they are not convenient for any kind of processing at the semantics level. I wouldn't go as far as stating that reasoning is impossible, but it has to be handled by an additional layer (see for example https://arxiv.org/abs/1307.2603)

That being said, it all depends on the level of intelligence that we need/want to implement on the server side, if any. I would be happy with a very simple server, merely providing CRUD operations on a set of semantically-described resources, and leave it to the client to do smart stuff with those. To quote Ruben Verborgh, we can aim at "a Web on which clients possess more intelligence than the servers they use".

**Comment by Mec-iS** [comment]
@pchampin 
> I would be happy with a very simple server, merely providing CRUD operations on a set of semantically-described resources, and leave it to the client to do smart stuff with those.

Yeah definitely, same idea in my starting annotations. the "client" (that in many cases will be just another layer of service for the "end-user") will actually handle the "intelligent" part. Let's discuss this matter when we will have a well-based prototype for an HYDRA server, so we can decide how to improve it and make it work with the client.

**Comment by Mec-iS** [comment]
temporary closing. To be reopened in a later phase.
