### ISSUE TITLE
Implement type annotations using mypy

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#60]
Try to refactor the codebase by implementing type annotations and type checking before runtime using `mypy`

**Comment by aswinzz** [comment]
can i work on this issue?

**Comment by Mec-iS** [comment]
Sure. Accept the invitation to the Github team and [follow the guidelines](https://github.com/HTTP-APIs/hydrus/wiki/Starting-Material)

**Comment by vddesai1998** [comment]
Can I help with this issue if no one is working on it?

**Comment by Mec-iS** [comment]
In general,anybody can fork the repo and start working on the fork. Once you have something done we can consider opening a branch in which different people working on the same project can collaborate.

**Comment by Mec-iS** [comment]
Merged #96

**Comment by vddesai1998** [comment]
Hey @Mec-iS  why type annotations from app.py are removed?
Should I open a PR type annotating app.py?
I am not opening a issue because we already has this issue.

**Comment by xadahiya** [comment]
@vddesai1998  See #128
