### ISSUE TITLE
AttributeError while running setup.py

### ISSUE THREAD

**Issue by Dhairya3124** [HTTP-APIs/hydrus#605]
### I'm submitting a 
- [ x] bug report.
- [ ] feature request.

### Current Behaviour:

While running the setup.py file I'm encountering this error:
![image](https://user-images.githubusercontent.com/31827131/150698156-1a2b30b2-7ffc-4b32-86f2-aa2239f990bf.png)
OS: Ubuntu 20.04 LTS
Python Version: Python 3.8

### Environment:
OS: Ubuntu 20.04 LTS
Python Version: Python 3.8

### Do you want to work on this issue?
yes

**Comment by Mec-iS** [comment]
have you run `pip install --upgrade pip setuptools`? pip should be always at the latest version

**Comment by Dhairya3124** [comment]
> have you run `pip install --upgrade pip setuptools`? pip should be always at the latest version

Yes this resolved the problem. Thanks
