### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by redlif345** [HTTP-APIs/hydrus#609]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Snapshot:

![issue](https://user-images.githubusercontent.com/92918806/151492440-d7f00c49-253c-4e96-a9c7-e02ac1fd33bd.png)

### Environment:
 
* python version
* pip version
* OS details

**Comment by Mec-iS** [comment]
please upgrade your `pip` and `setuptools` to the latest version

**Comment by redlif345** [comment]
okk thank you
