### ISSUE TITLE
Typo in `demo.py` file

### ISSUE THREAD

**Issue by vrutik2809** [HTTP-APIs/hydrus#610]
### I'm submitting a 
- [x] bug report.

### Current Behaviour:
While executing the [demo.py](https://github.com/HTTP-APIs/hydrus/blob/develop/examples/hydrus-demo-server/demo.py) file, it throws the following error: `from gevent.wsgi import WSGIServer
ModuleNotFoundError: No module named 'gevent.wsgi'`

### Expected Behaviour:
The server should start running

### Steps to reproduce:
Run the [demo.py](https://github.com/HTTP-APIs/hydrus/blob/develop/examples/hydrus-demo-server/demo.py) file.

### Snapshot:
![image](https://user-images.githubusercontent.com/74986666/154818927-3dc918c4-1c28-414a-a09e-b845467e6091.png)

### Environment:
 
* python version - 3.10.2
* pip version - 22.0.3
* OS details
    - Name - Microsoft Windows 11 Home Single Language
    - Version - 10.0.22000 N/A Build 22000

### Do you want to work on this issue?

Yes

**Comment by Mec-iS** [comment]
which way you installed? did you use `poetry install`?

**Comment by vrutik2809** [comment]
No. I simply did `pip install -r requirements.txt`
