### ISSUE TITLE
Revamp Wiki

### ISSUE THREAD

**Issue by chrizandr** [HTTP-APIs/hydrus#72]
As most are aware, the wiki section is still very verbose and not beginner friendly. It would be great to have some refactoring done there to improve readability and help newcomer's in getting started.

Maybe something like the blog would be a good way to arrange ideas?
Please give some suggestions.

Adding for reference:
https://gsocchrizandr.wordpress.com/the-book-of-hydrus/

**Comment by Mec-iS** [comment]
In the [design page](https://github.com/HTTP-APIs/hydrus/wiki/Design) is missing the part in which the different subsets of classes and predicates are defined. Something like:
```
The different kinds of classes in the graph-database describe the different subsets of classes and relations between classes. There are two main subset of classes and predicates:
the Abstract and Instance classes: the first are concepts that are not directly used to instantiate resources, the second that do
The Abstract and Instance predicates: as in 1, predicates that relate Abstract classes are Abstract; the ones that relate instances are consequently Instance predicates
```

as pointed out by @hd41

**Comment by starlord1311** [comment]
@chrizandr @Mec-iS can i work on this?

**Comment by Mec-iS** [comment]
@starlord1311 this takes much insight in the workflow. I will do it

**Comment by sandeepsajan0** [comment]
hey @Mec-iS  as you mention above about two main subsets of classes and predicates are well defined [here](https://gsocchrizandr.wordpress.com/hydrus-models/). We can add this link to design page for a reference with a brief explanation.

**Comment by Mec-iS** [comment]
I think this should be moved to the WIKI repository https://github.com/HTTP-APIs/hydra-ecosystem-wiki
