### ISSUE TITLE
Python version is not specified.

### ISSUE THREAD

**Issue by nityanandagohain** [HTTP-APIs/hydrus#76]
In the readme of this project the version of python is not specified wheather it's python2 or python3. It will be nice if it is specified .

I think that this project is using python 2 . Please enlighten me if I am wrong.
Can I work on this issue and update the readme.

**Comment by xadahiya** [comment]
Hey @nityanandagohain , thanks for pointing it out. You need to use python3, i'll add this info to the wiki.

**Comment by xadahiya** [comment]
Closed in #77

**Comment by nityanandagohain** [comment]
@xadahiya  but please can I update the readme since I am new to this community and I have already setup this project in my pc and got it running.

**Comment by xadahiya** [comment]
@nityanandagohain already merged the PR. 😅

**Comment by xadahiya** [comment]
Don't worry you'll have a lot to work on pretty soon. Till then try to understand the project structure and how it works. 
Cheers! 😄

**Comment by nityanandagohain** [comment]
Thank you ! 👍

**Comment by chrizandr** [comment]
Also as a note, although most of the code was written in Python3, it is still compatible with Python2.

**Comment by xadahiya** [comment]
Yeah!

**Comment by Mec-iS** [comment]
NOTE: As a generic rule, everything should work and be tested for Python 3.5.2 and above.
