### ISSUE TITLE
Coding Conventions

### ISSUE THREAD

**Issue by yashLadha** [HTTP-APIs/hydrus#79]
Currently the code has many functions that doesn't follow proper naming conventions and also lines are greater than 79 characters, which is not according to Conventions and standards followed. 

Some of the functions with improper naming convention : 

![image](https://user-images.githubusercontent.com/18033231/36139099-3ddc9a16-10c2-11e8-8a48-888a8b69dc70.png)

__Working status__:
Yes I am working on it.

**Comment by yashLadha** [comment]
Ping @chrizandr @Mec-iS

**Comment by starlord1311** [comment]
@yashLadha  can i work on this?

**Comment by yashLadha** [comment]
@starlord1311 I have clearly mentioned in the issue description that i am working on this. I am waiting for the response @chrizandr @Mec-iS

**Comment by Mec-iS** [comment]
NOTE: I would prefer to stick to PEP-8. In particular functions' names should be lowercase and underscored (not camel-case). You can use `pylint` as checker. 

Furthermore, also implementing autodocumentation with Sphinx should be considered.

**Comment by yashLadha** [comment]
Sure, I will try to do proper convention and for Sphinx i have to learn it and will update you on it @Mec-iS  😄

**Comment by yashLadha** [comment]
@Mec-iS Should I also change the docstrings , as they are stretching to length > 79. This way i will get a better understanding of codebase as well. Views?

**Comment by Mec-iS** [comment]
Not a great issue. I think we can leave the lines length as it is now. See [here](http://hilton.org.uk/blog/source-code-line-length):

> 125 characters per line is the real de facto coding standard for maximum line length these days, because this is the maximum number of characters that you can see in the GitHub diff view. This used to be 119 characters, but the page layout changed.

Usually 89 or 99 is also accepted. 79 could be too short for current screen sizes.

**Comment by yashLadha** [comment]
But a you mentioned, in the PEP-8 conventions it is of 79 length and pylint follows the same. So should i lint the code according to PEP-8 conventions or leave it as it is and work on the renaming of functions.

**Comment by chrizandr** [comment]
The values in pylint for number of characters can be modified. It is not a strict convention. Most codebases nowadays require more than 79 characters. There are also some lines that cannot be shortened. It's better to leave it as it is.

**Comment by yashLadha** [comment]
Sure @chrizandr . Will make the updates.

**Comment by IamRaviTejaG** [comment]
@yashLadha Correct me if I'm wrong, but the '\' character for line continuations is frowned upon. Instead, use of parenthesis is encouraged, see here: https://www.python.org/dev/peps/pep-0008/#indentation

**Comment by Mec-iS** [comment]
Merged #117
