### ISSUE TITLE
Server is not stoppable

### ISSUE THREAD

**Issue by nityanandagohain** [HTTP-APIs/hydrus#80]
Currently we are using serve_forever() which gives following error when it get's a keyboard interrupt.

![screenshot from 2018-02-13 16-03-36](https://user-images.githubusercontent.com/26831659/36146417-93f5f1e6-10da-11e8-8081-c2de2a7828e3.png)

I want to work on this.
Some help will be very much appreciated.

**Comment by xadahiya** [comment]
Fixed in #81
