### ISSUE TITLE
Implementing autodocumentation in readthedocs

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#82]
https://wiki.python.org/moin/DocumentationTools

Autobuilding of documentation should be implemented with Sphinx or similar tool, and the documentation be published at https://readthedocs.org/

Docstrings and functions' signatures should be ported to supported formats.

**Comment by sandeepsajan0** [comment]
@Mec-iS  I want to work on this issue. Can I proceed?

**Comment by Mec-iS** [comment]
Sure. in general anybody can work on anything accordingly to his/her skills. Try your implementation, then submit a PR and we will suggest how to proceed or if there is something to fix. Fork the master, add your code, documentation and tests and submit a pull request. You can find a very interesting [how-to about Github workflow here](https://guides.github.com/introduction/flow/)

**Comment by Mec-iS** [comment]
Moved to new repository https://github.com/HTTP-APIs/documentation-hydrus

Reference >>> https://github.com/HTTP-APIs/documentation-hydrus/issues/1
