### ISSUE TITLE
Evolving database models

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#9]
After a starting implementation that applies some nice basic concepts, we need to find the right way for improving the models. 

## Temporary models segregation
I segregated the models for properties (`AbstractPropery` and `Property`) but I don't exclude that in the future they will be in the same table as records that inherits from the same base model. A similar thing can be designed for records in the `Graph` relation, we may have three different "kinds" of triples that inherits from the same "Triple" class and are then stored in the same table.

## How to implement Graph
For `Graph` that is really sparse a this moment. At first I came out with a solution like:

> Add an Entity() class to build up every type of triple (instantiated, abstracted, terminated). To have for every record something like a triple:
>> (Entity(Instance('A')), Entity(Property('B')), Entity(Terminal('C'))).

> Or split the triple into tuples: 
>> (Entity(Instance('A')), Entity(Property('B'))) , (Entity(Property('B')), Entity(Terminal('C'))).

> These solutions can lead to difficulties in querying by joining though.

Check this interesting [video about optimizing hashmaps](https://www.youtube.com/watch?v=npw4s1QTmPg) for ideas.

**Comment by Mec-iS** [comment]
Should we inplement SQLAlchemy inheritance?

Please take a look about how to make inheritance with SQLAlchemy models: http://docs.sqlalchemy.org/en/latest/orm/inheritance.html

Probably we should have something like: 
```
class BaseProperty(models.Model):
     pass

class InstancesProperty(BaseProperty):
    pass

class AbstractProperty(BaseProperty):
    pass
```
Check also advantages/disadvantages of this schema for different querying strategies.

**Comment by chrizandr** [comment]
**_Inheritance can be applied to both Properties as well as Graph._**

The inheritance type can be either a _Joint Table Inheritance_ or a _Single Table Inheritance_. 
For now a _Single Table Inheritance_ would be preferable. This is becuase _Joint Inheritance_ would require a **JOIN** operation every time a table is queried. In _Single Inheritance_ all instances of Properties and graph would be stored in single tables. 

Here is the class hierarchy I propose:
For the **Property** Table:
As mentioned by @Mec-iS , it would be advantageous to implement inheritance in properties for easier querying over the graph.

![untitled diagram](https://user-images.githubusercontent.com/10355740/26924192-591d8d1e-4c62-11e7-9c2f-5608a8169549.png)

Similarly for the **Graph** Table:
Inheritance in the Graph Table for different kinds of triples would further simplify querying based on the triple objects. The below schema is not limited to three objects, but inheritance of triples is favourable.

![untitled diagram 1](https://user-images.githubusercontent.com/10355740/26924406-56e9a338-4c63-11e7-847e-5a86eb1888b1.png)

**NOTE: These are not the only type of triples possible. They are however the most common ones. More can be added at a later stage.** 

I will create a PR soon to implement these Models and we can start storing random objects in them as needed.

**Comment by xadahiya** [comment]
```python

class Graph(Base):
    """Model for a graph that store triples of instance from the other models to map relationships."""

    __tablename__ = "graph"

    id = Column(Integer, primary_key=True)
    type = Column(String)

    __mapper_args__ = {
        'polymorphic_identity': 'graph',
        'polymorphic_on': type
    }


class GraphCAC(Graph):
    """Graph model for Class >> AbstractProperty >> Class."""

    __tablename__ = 'graphcac'
    id = Column(Integer, ForeignKey('graph.id'), primary_key=True)
    subject = Column(Integer, ForeignKey("classes.id"))
    predicate = Column(Integer, ForeignKey("property.id"))
    object_ = Column(Integer, ForeignKey("classes.id"))

    __mapper_args__ = {
        'polymorphic_identity': 'graphcac',
    }

    def __repr__(self):
        """Verbose object name."""
        return "<subject='%s', predicate='%s', object_='%s'>" % (self.subject, self.predicate, self.object_)


class GraphIAC(Graph):
    """Graph model for Instance >> AbstractProperty >> Class."""

    __tablename__ = 'graphiac'
    id = Column(Integer, ForeignKey('graph.id'), primary_key=True)
    subject = Column(Integer, ForeignKey("instances.id"))
    predicate = Column(Integer, ForeignKey("property.id"))
    object_ = Column(Integer, ForeignKey("classes.id"))

    __mapper_args__ = {
        'polymorphic_identity': 'graphiac',
    }

    def __repr__(self):
        """Verbose object name."""
        return "<subject='%s', predicate='%s', object_='%s'>" % (self.subject, self.predicate, self.object_)


class GraphIII(Graph):
    """Graph model for Instance >> InstanceProperty >> Instance."""

    __tablename__ = 'graphiii'
    id = Column(Integer, ForeignKey('graph.id'), primary_key=True)
    subject = Column(Integer, ForeignKey("instances.id"))
    predicate = Column(Integer, ForeignKey("property.id"))
    object_ = Column(Integer, ForeignKey("instances.id"))

    __mapper_args__ = {
        'polymorphic_identity': 'graphiii',
    }

    def __repr__(self):
        """Verbose object name."""
        return "<subject='%s', predicate='%s', object_='%s'>" % (self.subject, self.predicate, self.object_)


class GraphIIT(Graph):
    """Graph model for Instance >> InstanceProperty >> Terminal."""

    __tablename__ = 'graphiit'
    id = Column(Integer, ForeignKey('graph.id'), primary_key=True)
    subject = Column(Integer, ForeignKey("instances.id"))
    predicate = Column(Integer, ForeignKey("property.id"))
    object_ = Column(Integer, ForeignKey("terminals.id"))

    __mapper_args__ = {
        'polymorphic_identity': 'graphiit',
    }

    def __repr__(self):
        """Verbose object name."""
        return "<subject='%s', predicate='%s', object_='%s'>" % (self.subject, self.predicate, self.object_)

```

The database design proposed by @chrizandr uses a schema like this for defining various type of Graphs. However, this approach has some issues. 

The main issue is 
**It makes implementation of `get(id)` very complicated.** Earlier we were using `instances.id` as a unique parameter to fetch the data but this approach makes it a bit difficult as in `GraphCAC` the subject is `classes.id` while in rest of the graphs `instances.id` is the subject which makes it really complicated. For this to work there needs to be unique ids across both the tables (classes and instances) or we'll have to  allow multiple objects with same ids to exist in the database. I think we should reconsider our options here.
@Mec-iS @chrizandr

**Comment by chrizandr** [comment]
GraphCAC is mostly used for parent and child class relationships or class restrictions. For ex: "Student isSubClass Person" is one possible triple. It mostly used to store graphical data. But we must use it at a later stage to ensure that instances are in accordance with the Graph definitions.

Other than that I agree that the get function would be a little complicated. But I feel that it is for the better. In such a design, subjects that are terminals, instances and classes are handled separately. Unique IDs across both tables would make the query easier, but we would still need to check different cases and exceptions for terminals, instances and classes separately. 
That was my only concern when I opted for this design.

Let me know your comments :)

**Comment by Mec-iS** [comment]
@chrizandr @xadahiya
For now focus on "instance data", no RDF sub-classing. At the moment the only `AbstractProperty` we need is `SubSystemType isComponentOf Spacecraft` I think, the others are Instance Properties about resources. The interaction with the RDF vocabularies is really limited. 
Hydra is about describing resources in the API, the RDF part is something really complex that we will tackle later on, so reduce the RDF to the minimum to serve the resources. We are creating an API server at the moment, we cannot get into the big work of creating a fully featured RDF datastore (that is not the objective of the project). Try to keep the triples approach but in the boundaries of the Hydra spec, adding some RDF definitions when possible and not too costly.

**Comment by Mec-iS** [comment]
moved to #47
