### ISSUE TITLE
Refactoring key validation in a dictionary body

### ISSUE THREAD

**Issue by anubhav253** [HTTP-APIs/hydrus#95]
### I'm submitting a 
- [x] Enhancement Request.

### Current Behaviour:

We are using try catch to check every key in the dictionary and assigning it to new variable.
rather to validate the current payload we should have a generic function in which we can pass the key and value to check and it will return the keys or exception from that function 
[Current Sample code structure] (https://ibb.co/ciM4Vn)

### Do you want to work on this issue ?

yes
@Mec-iS -can you provide any suggestion here

**Comment by Mec-iS** [comment]
@anubhav253 Can you point the line in the codebase where you spotted the issue (you can use the `+` beside the line to directly open a issue or copy the permalink). For the workflow is better to reference in the code in Github itself.

**Comment by anubhav253** [comment]
@Mec-iS - Yeah sure i will follow the steps from next issues. for now here is the code reference for the above description https://github.com/HTTP-APIs/hydrus/blob/fe55ee5997a26ec0a57e2bdfe04a5d6656301de7/hydrus/hydraspec/doc_maker.py#L35

**Comment by Mec-iS** [comment]
Yeah that part is cluncky. We should have a dictionary mapping `keys` to `error_mesages` and then loop through `keys()`. If key is not in keys, raise the message.

**Comment by anubhav253** [comment]
yea, we can have function where we pass the keys and the payload in which we need to check the keys. Here whatever keys required from whichever payload will be store in dictionary which will make easier for maintenance.  the overview of function is provided below.  can i start working on this for gsoc  preparations ?

`def inputKeyCheck(body, key):
    try:
        return doc[key]
    except KeyError:
        raise SyntaxError("The API Documentation must have [" + key + "]");`

**Comment by Mec-iS** [comment]
You don't need to ask for permission. Fork `master`, submit a PR and ask for reviewing

**Comment by anubhav253** [comment]
yea, sure I will follow the procedure suggested here .

**Comment by alohamora** [comment]
Hi @Mec-iS @xadahiya ...can I contribute to this issue??

**Comment by xadahiya** [comment]
@alohamora  you don't need to ask for permission. Just fork the repo and start working on the issue. Submit a PR when you're done.

**Comment by anubhav253** [comment]
Hii @Mec-iS  its done and I have raised a pull request can you verify the changes here.

**Comment by Mec-iS** [comment]
Merged #116
