### ISSUE TITLE
Extensively document the methods

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#98]
### I'm submitting a 
- [v] feature request.

### Current Behaviour
Methods' docstring do not list inputs in signatures

### Expected Behaviour:
Every method should have a docstring in this format: 
```
"""
Extensive explanation of what the method does.

:param input1: description of the input1
:param input2: description of input2
:return return_type: description of returned object
"""
```

**Comment by nityanandagohain** [comment]
can I work on this.

**Comment by WickedBrat** [comment]
@Mec-iS I think it's better if we create a list of files and assign each file to a beginner. That way every beginner get to learn. 
/cc @xadahiya suggestions

**Comment by xadahiya** [comment]
I don't think it's a good idea. As every person has a different writing style, assigning different files to different people can create a lot of variations in doc strings.

**Comment by Mec-iS** [comment]
Work on Github is distributed by definition. Everybody that want to participate can provide a PR and then PRs for the same issue can be confronted. This way it is the best code that is merged, so it may happen that a developer wrote one docstring better than anoher, and the best docstrings can be picked and put in the same merged PR.

**Comment by nityanandagohain** [comment]
@WickedBrat if you want you can work  on this . I am having test this week .

**Comment by sandeepsajan0** [comment]
@Mec-iS  As I can understand, you want to change every file's every function's docstring with this(above given) type of format. Am I right and it is not necessary to update all the files by the same person?

**Comment by py-ranoid** [comment]
Since, I'm going to have to understand `hydrus/app.py` inside-out to migrate to Falcon, should I document the existing Flask-based functions with docstrings before I go about migrating to Falcon ?

**Comment by IamRaviTejaG** [comment]
@Mec-iS Can you assign me this? I'd like to work on this.

**Comment by Mec-iS** [comment]
@sandeepsajan0 exactly. A work of editing will be done in the PR

**Comment by Mec-iS** [comment]
This is still to be done for all the other modules

**Comment by py-ranoid** [comment]
@Mec-iS Working on documenting app.py
